"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateNanoBananaImage = generateNanoBananaImage;
const genai_1 = require("@google/genai");
const client_s3_1 = require("@aws-sdk/client-s3");
const s3_request_presigner_1 = require("@aws-sdk/s3-request-presigner");
const s3 = new client_s3_1.S3Client({ region: process.env.AWS_REGION || 'us-east-1' });
async function generateNanoBananaImage(description, scenePosition, userId, timestamp, seed, signedUrl) {
    try {
        // Initialize Google GenAI
        const genAI = new genai_1.GoogleGenAI({
            apiKey: process.env.GEMINI_API_KEY,
        });
        console.log(`🎨  genai - Calling Gemini Nano Banana for image generation in scene ${scenePosition}...`);
        console.log('- Prompt:', description);
        console.log('- Model: gemini-2.5-flash-image-preview');
        console.log('- User ID:', userId);
        console.log('- Timestamp:', timestamp);
        console.log('- Seed:', seed);
        // Generate an image using Gemini Nano Banana
        console.log('🎨 genai - Generating image from text...');
        const prompt = `${description} - photorealistic, film grain, 50mm lens, dramatic rim light`;
        // Retry logic for image generation
        let response;
        let retryCount = 0;
        const maxRetries = 5;
        const timeoutMs = 60000; // 60 seconds timeout
        while (retryCount < maxRetries) {
            try {
                console.log(`🎨 genai - Attempt ${retryCount + 1}/${maxRetries} for scene ${scenePosition}`);
                response = (await Promise.race([
                    genAI.models.generateImages({
                        model: 'imagen-4.0-generate-001',
                        prompt,
                        config: {
                            numberOfImages: 1,
                            aspectRatio: '9:16',
                            personGeneration: genai_1.PersonGeneration.ALLOW_ALL,
                        },
                    }),
                    new Promise((_, reject) => setTimeout(() => reject(new Error('Image generation timeout')), timeoutMs)),
                ]));
                console.log('🎨 genai - Image generation API call completed');
                console.log('🔍 genai - Response received, checking for generated images...');
                console.log('🔍 genai - Generated images count:', response.generatedImages?.length || 0);
                console.log('genai - promptFeedback:', response?.promptFeedback);
                console.log('genai - safetyRatings:', response?.safetyRatings);
                console.log('genai - blockedReason:', response?.blockedReason || response?.finishReason);
                if (!response.generatedImages ||
                    response.generatedImages.length === 0) {
                    throw new Error('No images generated by the API');
                }
                // If we get here, the generation was successful
                console.log('✅ genai - Image generation successful');
                break;
            }
            catch (error) {
                retryCount++;
                console.error(`❌ genai - Image generation attempt ${retryCount} failed:`, error);
                // If we've exhausted retries, throw the error
                if (retryCount >= maxRetries) {
                    console.error(`❌ genai - All ${maxRetries} attempts failed for scene ${scenePosition}`);
                    throw error;
                }
                // Wait before retrying (exponential backoff)
                const waitTime = Math.min(1000 * Math.pow(2, retryCount - 1), 5000);
                console.log(`⏳ genai - Waiting ${waitTime}ms before retry...`);
                await new Promise((resolve) => setTimeout(resolve, waitTime));
            }
        }
        let s3Key = '';
        for (const generatedImage of response.generatedImages || []) {
            let imgBytes = generatedImage.image?.imageBytes;
            const imageBuffer = Buffer.from(imgBytes || '', 'base64');
            console.log('genai - Image saved as gemini-native-image.png');
            // if you want to always store JPEG, actually re-encode with `sharp`.
            // otherwise keep the model's format:
            s3Key = `${userId}/${timestamp}.scene-${scenePosition}.png`;
            console.log('genai - Uploading image to S3', s3Key);
            await s3.send(new client_s3_1.PutObjectCommand({
                Bucket: process.env.VIDEO_PARTS_BUCKET_NAME,
                Key: s3Key,
                Body: imageBuffer,
                ContentType: 'image/png',
            }));
            console.log('genai - Image uploaded to S3', s3Key);
        }
        // Generate URL based on scenes count
        if (signedUrl) {
            // Return presigned URL for single scene
            const getObjectCommand = new client_s3_1.GetObjectCommand({
                Bucket: process.env.VIDEO_PARTS_BUCKET_NAME,
                Key: s3Key,
            });
            const presignedUrl = await (0, s3_request_presigner_1.getSignedUrl)(s3, getObjectCommand, {
                expiresIn: 36000, // 10 hours
            });
            console.log('🖼️ genai - Generated and uploaded image with presigned URL:', presignedUrl);
            return presignedUrl;
        }
        return '';
    }
    catch (error) {
        console.error(`❌ genai - Error in generateNanoBananaImage for scene ${scenePosition}:`, error);
        if (error && typeof error === 'object' && 'message' in error) {
            console.error('genai - Error message:', error.message);
            console.error('genai - Error name:', error.name);
            console.error('genai - Error stack:', error.stack);
        }
        throw error;
    }
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW1hZ2VOYW5vQmFuYW5hLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiaW1hZ2VOYW5vQmFuYW5hLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7O0FBaUJBLDBEQXVLQztBQXhMRCx5Q0FBOEQ7QUFDOUQsa0RBSTRCO0FBQzVCLHdFQUE2RDtBQUU3RCxNQUFNLEVBQUUsR0FBRyxJQUFJLG9CQUFRLENBQUMsRUFBRSxNQUFNLEVBQUUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxVQUFVLElBQUksV0FBVyxFQUFFLENBQUMsQ0FBQztBQVNwRSxLQUFLLFVBQVUsdUJBQXVCLENBQzNDLFdBQW1CLEVBQ25CLGFBQXFCLEVBQ3JCLE1BQWMsRUFDZCxTQUFpQixFQUNqQixJQUFZLEVBQ1osU0FBbUI7SUFFbkIsSUFBSSxDQUFDO1FBQ0gsMEJBQTBCO1FBQzFCLE1BQU0sS0FBSyxHQUFHLElBQUksbUJBQVcsQ0FBQztZQUM1QixNQUFNLEVBQUUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxjQUFlO1NBQ3BDLENBQUMsQ0FBQztRQUVILE9BQU8sQ0FBQyxHQUFHLENBQ1Qsd0VBQXdFLGFBQWEsS0FBSyxDQUMzRixDQUFDO1FBQ0YsT0FBTyxDQUFDLEdBQUcsQ0FBQyxXQUFXLEVBQUUsV0FBVyxDQUFDLENBQUM7UUFDdEMsT0FBTyxDQUFDLEdBQUcsQ0FBQyx5Q0FBeUMsQ0FBQyxDQUFDO1FBQ3ZELE9BQU8sQ0FBQyxHQUFHLENBQUMsWUFBWSxFQUFFLE1BQU0sQ0FBQyxDQUFDO1FBQ2xDLE9BQU8sQ0FBQyxHQUFHLENBQUMsY0FBYyxFQUFFLFNBQVMsQ0FBQyxDQUFDO1FBQ3ZDLE9BQU8sQ0FBQyxHQUFHLENBQUMsU0FBUyxFQUFFLElBQUksQ0FBQyxDQUFDO1FBRTdCLDZDQUE2QztRQUM3QyxPQUFPLENBQUMsR0FBRyxDQUFDLDBDQUEwQyxDQUFDLENBQUM7UUFFeEQsTUFBTSxNQUFNLEdBQUcsR0FBRyxXQUFXLDhEQUE4RCxDQUFDO1FBRTVGLG1DQUFtQztRQUNuQyxJQUFJLFFBQVEsQ0FBQztRQUNiLElBQUksVUFBVSxHQUFHLENBQUMsQ0FBQztRQUNuQixNQUFNLFVBQVUsR0FBRyxDQUFDLENBQUM7UUFDckIsTUFBTSxTQUFTLEdBQUcsS0FBSyxDQUFDLENBQUMscUJBQXFCO1FBRTlDLE9BQU8sVUFBVSxHQUFHLFVBQVUsRUFBRSxDQUFDO1lBQy9CLElBQUksQ0FBQztnQkFDSCxPQUFPLENBQUMsR0FBRyxDQUNULHNCQUNFLFVBQVUsR0FBRyxDQUNmLElBQUksVUFBVSxjQUFjLGFBQWEsRUFBRSxDQUM1QyxDQUFDO2dCQUVGLFFBQVEsR0FBRyxDQUFDLE1BQU0sT0FBTyxDQUFDLElBQUksQ0FBQztvQkFDN0IsS0FBSyxDQUFDLE1BQU0sQ0FBQyxjQUFjLENBQUM7d0JBQzFCLEtBQUssRUFBRSx5QkFBeUI7d0JBQ2hDLE1BQU07d0JBQ04sTUFBTSxFQUFFOzRCQUNOLGNBQWMsRUFBRSxDQUFDOzRCQUNqQixXQUFXLEVBQUUsTUFBTTs0QkFDbkIsZ0JBQWdCLEVBQUUsd0JBQWdCLENBQUMsU0FBUzt5QkFDN0M7cUJBQ0YsQ0FBQztvQkFDRixJQUFJLE9BQU8sQ0FBQyxDQUFDLENBQUMsRUFBRSxNQUFNLEVBQUUsRUFBRSxDQUN4QixVQUFVLENBQ1IsR0FBRyxFQUFFLENBQUMsTUFBTSxDQUFDLElBQUksS0FBSyxDQUFDLDBCQUEwQixDQUFDLENBQUMsRUFDbkQsU0FBUyxDQUNWLENBQ0Y7aUJBQ0YsQ0FBQyxDQUFRLENBQUM7Z0JBRVgsT0FBTyxDQUFDLEdBQUcsQ0FBQyxnREFBZ0QsQ0FBQyxDQUFDO2dCQUM5RCxPQUFPLENBQUMsR0FBRyxDQUNULGdFQUFnRSxDQUNqRSxDQUFDO2dCQUNGLE9BQU8sQ0FBQyxHQUFHLENBQ1Qsb0NBQW9DLEVBQ3BDLFFBQVEsQ0FBQyxlQUFlLEVBQUUsTUFBTSxJQUFJLENBQUMsQ0FDdEMsQ0FBQztnQkFFRixPQUFPLENBQUMsR0FBRyxDQUFDLHlCQUF5QixFQUFFLFFBQVEsRUFBRSxjQUFjLENBQUMsQ0FBQztnQkFDakUsT0FBTyxDQUFDLEdBQUcsQ0FBQyx3QkFBd0IsRUFBRSxRQUFRLEVBQUUsYUFBYSxDQUFDLENBQUM7Z0JBQy9ELE9BQU8sQ0FBQyxHQUFHLENBQ1Qsd0JBQXdCLEVBQ3hCLFFBQVEsRUFBRSxhQUFhLElBQUksUUFBUSxFQUFFLFlBQVksQ0FDbEQsQ0FBQztnQkFFRixJQUNFLENBQUMsUUFBUSxDQUFDLGVBQWU7b0JBQ3pCLFFBQVEsQ0FBQyxlQUFlLENBQUMsTUFBTSxLQUFLLENBQUMsRUFDckMsQ0FBQztvQkFDRCxNQUFNLElBQUksS0FBSyxDQUFDLGdDQUFnQyxDQUFDLENBQUM7Z0JBQ3BELENBQUM7Z0JBRUQsZ0RBQWdEO2dCQUNoRCxPQUFPLENBQUMsR0FBRyxDQUFDLHVDQUF1QyxDQUFDLENBQUM7Z0JBQ3JELE1BQU07WUFDUixDQUFDO1lBQUMsT0FBTyxLQUFLLEVBQUUsQ0FBQztnQkFDZixVQUFVLEVBQUUsQ0FBQztnQkFDYixPQUFPLENBQUMsS0FBSyxDQUNYLHNDQUFzQyxVQUFVLFVBQVUsRUFDMUQsS0FBSyxDQUNOLENBQUM7Z0JBRUYsOENBQThDO2dCQUM5QyxJQUFJLFVBQVUsSUFBSSxVQUFVLEVBQUUsQ0FBQztvQkFDN0IsT0FBTyxDQUFDLEtBQUssQ0FDWCxpQkFBaUIsVUFBVSw4QkFBOEIsYUFBYSxFQUFFLENBQ3pFLENBQUM7b0JBQ0YsTUFBTSxLQUFLLENBQUM7Z0JBQ2QsQ0FBQztnQkFFRCw2Q0FBNkM7Z0JBQzdDLE1BQU0sUUFBUSxHQUFHLElBQUksQ0FBQyxHQUFHLENBQUMsSUFBSSxHQUFHLElBQUksQ0FBQyxHQUFHLENBQUMsQ0FBQyxFQUFFLFVBQVUsR0FBRyxDQUFDLENBQUMsRUFBRSxJQUFJLENBQUMsQ0FBQztnQkFDcEUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxxQkFBcUIsUUFBUSxvQkFBb0IsQ0FBQyxDQUFDO2dCQUMvRCxNQUFNLElBQUksT0FBTyxDQUFDLENBQUMsT0FBTyxFQUFFLEVBQUUsQ0FBQyxVQUFVLENBQUMsT0FBTyxFQUFFLFFBQVEsQ0FBQyxDQUFDLENBQUM7WUFDaEUsQ0FBQztRQUNILENBQUM7UUFFRCxJQUFJLEtBQUssR0FBRyxFQUFFLENBQUM7UUFFZixLQUFLLE1BQU0sY0FBYyxJQUFJLFFBQVEsQ0FBQyxlQUFlLElBQUksRUFBRSxFQUFFLENBQUM7WUFDNUQsSUFBSSxRQUFRLEdBQUcsY0FBYyxDQUFDLEtBQUssRUFBRSxVQUFVLENBQUM7WUFDaEQsTUFBTSxXQUFXLEdBQUcsTUFBTSxDQUFDLElBQUksQ0FBQyxRQUFRLElBQUksRUFBRSxFQUFFLFFBQVEsQ0FBQyxDQUFDO1lBRTFELE9BQU8sQ0FBQyxHQUFHLENBQUMsZ0RBQWdELENBQUMsQ0FBQztZQUU5RCxxRUFBcUU7WUFDckUscUNBQXFDO1lBQ3JDLEtBQUssR0FBRyxHQUFHLE1BQU0sSUFBSSxTQUFTLFVBQVUsYUFBYSxNQUFNLENBQUM7WUFFNUQsT0FBTyxDQUFDLEdBQUcsQ0FBQywrQkFBK0IsRUFBRSxLQUFLLENBQUMsQ0FBQztZQUVwRCxNQUFNLEVBQUUsQ0FBQyxJQUFJLENBQ1gsSUFBSSw0QkFBZ0IsQ0FBQztnQkFDbkIsTUFBTSxFQUFFLE9BQU8sQ0FBQyxHQUFHLENBQUMsdUJBQXdCO2dCQUM1QyxHQUFHLEVBQUUsS0FBSztnQkFDVixJQUFJLEVBQUUsV0FBVztnQkFDakIsV0FBVyxFQUFFLFdBQVc7YUFDekIsQ0FBQyxDQUNILENBQUM7WUFFRixPQUFPLENBQUMsR0FBRyxDQUFDLDhCQUE4QixFQUFFLEtBQUssQ0FBQyxDQUFDO1FBQ3JELENBQUM7UUFFRCxxQ0FBcUM7UUFDckMsSUFBSSxTQUFTLEVBQUUsQ0FBQztZQUNkLHdDQUF3QztZQUN4QyxNQUFNLGdCQUFnQixHQUFHLElBQUksNEJBQWdCLENBQUM7Z0JBQzVDLE1BQU0sRUFBRSxPQUFPLENBQUMsR0FBRyxDQUFDLHVCQUF3QjtnQkFDNUMsR0FBRyxFQUFFLEtBQUs7YUFDWCxDQUFDLENBQUM7WUFFSCxNQUFNLFlBQVksR0FBRyxNQUFNLElBQUEsbUNBQVksRUFBQyxFQUFFLEVBQUUsZ0JBQWdCLEVBQUU7Z0JBQzVELFNBQVMsRUFBRSxLQUFLLEVBQUUsV0FBVzthQUM5QixDQUFDLENBQUM7WUFFSCxPQUFPLENBQUMsR0FBRyxDQUNULDhEQUE4RCxFQUM5RCxZQUFZLENBQ2IsQ0FBQztZQUVGLE9BQU8sWUFBWSxDQUFDO1FBQ3RCLENBQUM7UUFFRCxPQUFPLEVBQUUsQ0FBQztJQUNaLENBQUM7SUFBQyxPQUFPLEtBQUssRUFBRSxDQUFDO1FBQ2YsT0FBTyxDQUFDLEtBQUssQ0FDWCx3REFBd0QsYUFBYSxHQUFHLEVBQ3hFLEtBQUssQ0FDTixDQUFDO1FBQ0YsSUFBSSxLQUFLLElBQUksT0FBTyxLQUFLLEtBQUssUUFBUSxJQUFJLFNBQVMsSUFBSSxLQUFLLEVBQUUsQ0FBQztZQUM3RCxPQUFPLENBQUMsS0FBSyxDQUFDLHdCQUF3QixFQUFFLEtBQUssQ0FBQyxPQUFPLENBQUMsQ0FBQztZQUN2RCxPQUFPLENBQUMsS0FBSyxDQUFDLHFCQUFxQixFQUFHLEtBQWEsQ0FBQyxJQUFJLENBQUMsQ0FBQztZQUMxRCxPQUFPLENBQUMsS0FBSyxDQUFDLHNCQUFzQixFQUFHLEtBQWEsQ0FBQyxLQUFLLENBQUMsQ0FBQztRQUM5RCxDQUFDO1FBQ0QsTUFBTSxLQUFLLENBQUM7SUFDZCxDQUFDO0FBQ0gsQ0FBQyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IEdvb2dsZUdlbkFJLCBQZXJzb25HZW5lcmF0aW9uIH0gZnJvbSAnQGdvb2dsZS9nZW5haSc7XG5pbXBvcnQge1xuICBTM0NsaWVudCxcbiAgUHV0T2JqZWN0Q29tbWFuZCxcbiAgR2V0T2JqZWN0Q29tbWFuZCxcbn0gZnJvbSAnQGF3cy1zZGsvY2xpZW50LXMzJztcbmltcG9ydCB7IGdldFNpZ25lZFVybCB9IGZyb20gJ0Bhd3Mtc2RrL3MzLXJlcXVlc3QtcHJlc2lnbmVyJztcblxuY29uc3QgczMgPSBuZXcgUzNDbGllbnQoeyByZWdpb246IHByb2Nlc3MuZW52LkFXU19SRUdJT04gfHwgJ3VzLWVhc3QtMScgfSk7XG5cbmV4cG9ydCBpbnRlcmZhY2UgU2NlbmUge1xuICBkZXNjcmlwdGlvbjogc3RyaW5nO1xuICBkdXJhdGlvbjogbnVtYmVyO1xuICBuYXJyYXRpb246IHN0cmluZztcbiAgaWQ6IG51bWJlcjtcbn1cblxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIGdlbmVyYXRlTmFub0JhbmFuYUltYWdlKFxuICBkZXNjcmlwdGlvbjogc3RyaW5nLFxuICBzY2VuZVBvc2l0aW9uOiBudW1iZXIsXG4gIHVzZXJJZDogc3RyaW5nLFxuICB0aW1lc3RhbXA6IHN0cmluZyxcbiAgc2VlZDogbnVtYmVyLFxuICBzaWduZWRVcmw/OiBib29sZWFuLFxuKTogUHJvbWlzZTxzdHJpbmcgfCBudWxsPiB7XG4gIHRyeSB7XG4gICAgLy8gSW5pdGlhbGl6ZSBHb29nbGUgR2VuQUlcbiAgICBjb25zdCBnZW5BSSA9IG5ldyBHb29nbGVHZW5BSSh7XG4gICAgICBhcGlLZXk6IHByb2Nlc3MuZW52LkdFTUlOSV9BUElfS0VZISxcbiAgICB9KTtcblxuICAgIGNvbnNvbGUubG9nKFxuICAgICAgYPCfjqggIGdlbmFpIC0gQ2FsbGluZyBHZW1pbmkgTmFubyBCYW5hbmEgZm9yIGltYWdlIGdlbmVyYXRpb24gaW4gc2NlbmUgJHtzY2VuZVBvc2l0aW9ufS4uLmAsXG4gICAgKTtcbiAgICBjb25zb2xlLmxvZygnLSBQcm9tcHQ6JywgZGVzY3JpcHRpb24pO1xuICAgIGNvbnNvbGUubG9nKCctIE1vZGVsOiBnZW1pbmktMi41LWZsYXNoLWltYWdlLXByZXZpZXcnKTtcbiAgICBjb25zb2xlLmxvZygnLSBVc2VyIElEOicsIHVzZXJJZCk7XG4gICAgY29uc29sZS5sb2coJy0gVGltZXN0YW1wOicsIHRpbWVzdGFtcCk7XG4gICAgY29uc29sZS5sb2coJy0gU2VlZDonLCBzZWVkKTtcblxuICAgIC8vIEdlbmVyYXRlIGFuIGltYWdlIHVzaW5nIEdlbWluaSBOYW5vIEJhbmFuYVxuICAgIGNvbnNvbGUubG9nKCfwn46oIGdlbmFpIC0gR2VuZXJhdGluZyBpbWFnZSBmcm9tIHRleHQuLi4nKTtcblxuICAgIGNvbnN0IHByb21wdCA9IGAke2Rlc2NyaXB0aW9ufSAtIHBob3RvcmVhbGlzdGljLCBmaWxtIGdyYWluLCA1MG1tIGxlbnMsIGRyYW1hdGljIHJpbSBsaWdodGA7XG5cbiAgICAvLyBSZXRyeSBsb2dpYyBmb3IgaW1hZ2UgZ2VuZXJhdGlvblxuICAgIGxldCByZXNwb25zZTtcbiAgICBsZXQgcmV0cnlDb3VudCA9IDA7XG4gICAgY29uc3QgbWF4UmV0cmllcyA9IDU7XG4gICAgY29uc3QgdGltZW91dE1zID0gNjAwMDA7IC8vIDYwIHNlY29uZHMgdGltZW91dFxuXG4gICAgd2hpbGUgKHJldHJ5Q291bnQgPCBtYXhSZXRyaWVzKSB7XG4gICAgICB0cnkge1xuICAgICAgICBjb25zb2xlLmxvZyhcbiAgICAgICAgICBg8J+OqCBnZW5haSAtIEF0dGVtcHQgJHtcbiAgICAgICAgICAgIHJldHJ5Q291bnQgKyAxXG4gICAgICAgICAgfS8ke21heFJldHJpZXN9IGZvciBzY2VuZSAke3NjZW5lUG9zaXRpb259YCxcbiAgICAgICAgKTtcblxuICAgICAgICByZXNwb25zZSA9IChhd2FpdCBQcm9taXNlLnJhY2UoW1xuICAgICAgICAgIGdlbkFJLm1vZGVscy5nZW5lcmF0ZUltYWdlcyh7XG4gICAgICAgICAgICBtb2RlbDogJ2ltYWdlbi00LjAtZ2VuZXJhdGUtMDAxJyxcbiAgICAgICAgICAgIHByb21wdCxcbiAgICAgICAgICAgIGNvbmZpZzoge1xuICAgICAgICAgICAgICBudW1iZXJPZkltYWdlczogMSxcbiAgICAgICAgICAgICAgYXNwZWN0UmF0aW86ICc5OjE2JyxcbiAgICAgICAgICAgICAgcGVyc29uR2VuZXJhdGlvbjogUGVyc29uR2VuZXJhdGlvbi5BTExPV19BTEwsXG4gICAgICAgICAgICB9LFxuICAgICAgICAgIH0pLFxuICAgICAgICAgIG5ldyBQcm9taXNlKChfLCByZWplY3QpID0+XG4gICAgICAgICAgICBzZXRUaW1lb3V0KFxuICAgICAgICAgICAgICAoKSA9PiByZWplY3QobmV3IEVycm9yKCdJbWFnZSBnZW5lcmF0aW9uIHRpbWVvdXQnKSksXG4gICAgICAgICAgICAgIHRpbWVvdXRNcyxcbiAgICAgICAgICAgICksXG4gICAgICAgICAgKSxcbiAgICAgICAgXSkpIGFzIGFueTtcblxuICAgICAgICBjb25zb2xlLmxvZygn8J+OqCBnZW5haSAtIEltYWdlIGdlbmVyYXRpb24gQVBJIGNhbGwgY29tcGxldGVkJyk7XG4gICAgICAgIGNvbnNvbGUubG9nKFxuICAgICAgICAgICfwn5SNIGdlbmFpIC0gUmVzcG9uc2UgcmVjZWl2ZWQsIGNoZWNraW5nIGZvciBnZW5lcmF0ZWQgaW1hZ2VzLi4uJyxcbiAgICAgICAgKTtcbiAgICAgICAgY29uc29sZS5sb2coXG4gICAgICAgICAgJ/CflI0gZ2VuYWkgLSBHZW5lcmF0ZWQgaW1hZ2VzIGNvdW50OicsXG4gICAgICAgICAgcmVzcG9uc2UuZ2VuZXJhdGVkSW1hZ2VzPy5sZW5ndGggfHwgMCxcbiAgICAgICAgKTtcblxuICAgICAgICBjb25zb2xlLmxvZygnZ2VuYWkgLSBwcm9tcHRGZWVkYmFjazonLCByZXNwb25zZT8ucHJvbXB0RmVlZGJhY2spO1xuICAgICAgICBjb25zb2xlLmxvZygnZ2VuYWkgLSBzYWZldHlSYXRpbmdzOicsIHJlc3BvbnNlPy5zYWZldHlSYXRpbmdzKTtcbiAgICAgICAgY29uc29sZS5sb2coXG4gICAgICAgICAgJ2dlbmFpIC0gYmxvY2tlZFJlYXNvbjonLFxuICAgICAgICAgIHJlc3BvbnNlPy5ibG9ja2VkUmVhc29uIHx8IHJlc3BvbnNlPy5maW5pc2hSZWFzb24sXG4gICAgICAgICk7XG5cbiAgICAgICAgaWYgKFxuICAgICAgICAgICFyZXNwb25zZS5nZW5lcmF0ZWRJbWFnZXMgfHxcbiAgICAgICAgICByZXNwb25zZS5nZW5lcmF0ZWRJbWFnZXMubGVuZ3RoID09PSAwXG4gICAgICAgICkge1xuICAgICAgICAgIHRocm93IG5ldyBFcnJvcignTm8gaW1hZ2VzIGdlbmVyYXRlZCBieSB0aGUgQVBJJyk7XG4gICAgICAgIH1cblxuICAgICAgICAvLyBJZiB3ZSBnZXQgaGVyZSwgdGhlIGdlbmVyYXRpb24gd2FzIHN1Y2Nlc3NmdWxcbiAgICAgICAgY29uc29sZS5sb2coJ+KchSBnZW5haSAtIEltYWdlIGdlbmVyYXRpb24gc3VjY2Vzc2Z1bCcpO1xuICAgICAgICBicmVhaztcbiAgICAgIH0gY2F0Y2ggKGVycm9yKSB7XG4gICAgICAgIHJldHJ5Q291bnQrKztcbiAgICAgICAgY29uc29sZS5lcnJvcihcbiAgICAgICAgICBg4p2MIGdlbmFpIC0gSW1hZ2UgZ2VuZXJhdGlvbiBhdHRlbXB0ICR7cmV0cnlDb3VudH0gZmFpbGVkOmAsXG4gICAgICAgICAgZXJyb3IsXG4gICAgICAgICk7XG5cbiAgICAgICAgLy8gSWYgd2UndmUgZXhoYXVzdGVkIHJldHJpZXMsIHRocm93IHRoZSBlcnJvclxuICAgICAgICBpZiAocmV0cnlDb3VudCA+PSBtYXhSZXRyaWVzKSB7XG4gICAgICAgICAgY29uc29sZS5lcnJvcihcbiAgICAgICAgICAgIGDinYwgZ2VuYWkgLSBBbGwgJHttYXhSZXRyaWVzfSBhdHRlbXB0cyBmYWlsZWQgZm9yIHNjZW5lICR7c2NlbmVQb3NpdGlvbn1gLFxuICAgICAgICAgICk7XG4gICAgICAgICAgdGhyb3cgZXJyb3I7XG4gICAgICAgIH1cblxuICAgICAgICAvLyBXYWl0IGJlZm9yZSByZXRyeWluZyAoZXhwb25lbnRpYWwgYmFja29mZilcbiAgICAgICAgY29uc3Qgd2FpdFRpbWUgPSBNYXRoLm1pbigxMDAwICogTWF0aC5wb3coMiwgcmV0cnlDb3VudCAtIDEpLCA1MDAwKTtcbiAgICAgICAgY29uc29sZS5sb2coYOKPsyBnZW5haSAtIFdhaXRpbmcgJHt3YWl0VGltZX1tcyBiZWZvcmUgcmV0cnkuLi5gKTtcbiAgICAgICAgYXdhaXQgbmV3IFByb21pc2UoKHJlc29sdmUpID0+IHNldFRpbWVvdXQocmVzb2x2ZSwgd2FpdFRpbWUpKTtcbiAgICAgIH1cbiAgICB9XG5cbiAgICBsZXQgczNLZXkgPSAnJztcblxuICAgIGZvciAoY29uc3QgZ2VuZXJhdGVkSW1hZ2Ugb2YgcmVzcG9uc2UuZ2VuZXJhdGVkSW1hZ2VzIHx8IFtdKSB7XG4gICAgICBsZXQgaW1nQnl0ZXMgPSBnZW5lcmF0ZWRJbWFnZS5pbWFnZT8uaW1hZ2VCeXRlcztcbiAgICAgIGNvbnN0IGltYWdlQnVmZmVyID0gQnVmZmVyLmZyb20oaW1nQnl0ZXMgfHwgJycsICdiYXNlNjQnKTtcblxuICAgICAgY29uc29sZS5sb2coJ2dlbmFpIC0gSW1hZ2Ugc2F2ZWQgYXMgZ2VtaW5pLW5hdGl2ZS1pbWFnZS5wbmcnKTtcblxuICAgICAgLy8gaWYgeW91IHdhbnQgdG8gYWx3YXlzIHN0b3JlIEpQRUcsIGFjdHVhbGx5IHJlLWVuY29kZSB3aXRoIGBzaGFycGAuXG4gICAgICAvLyBvdGhlcndpc2Uga2VlcCB0aGUgbW9kZWwncyBmb3JtYXQ6XG4gICAgICBzM0tleSA9IGAke3VzZXJJZH0vJHt0aW1lc3RhbXB9LnNjZW5lLSR7c2NlbmVQb3NpdGlvbn0ucG5nYDtcblxuICAgICAgY29uc29sZS5sb2coJ2dlbmFpIC0gVXBsb2FkaW5nIGltYWdlIHRvIFMzJywgczNLZXkpO1xuXG4gICAgICBhd2FpdCBzMy5zZW5kKFxuICAgICAgICBuZXcgUHV0T2JqZWN0Q29tbWFuZCh7XG4gICAgICAgICAgQnVja2V0OiBwcm9jZXNzLmVudi5WSURFT19QQVJUU19CVUNLRVRfTkFNRSEsXG4gICAgICAgICAgS2V5OiBzM0tleSxcbiAgICAgICAgICBCb2R5OiBpbWFnZUJ1ZmZlcixcbiAgICAgICAgICBDb250ZW50VHlwZTogJ2ltYWdlL3BuZycsXG4gICAgICAgIH0pLFxuICAgICAgKTtcblxuICAgICAgY29uc29sZS5sb2coJ2dlbmFpIC0gSW1hZ2UgdXBsb2FkZWQgdG8gUzMnLCBzM0tleSk7XG4gICAgfVxuXG4gICAgLy8gR2VuZXJhdGUgVVJMIGJhc2VkIG9uIHNjZW5lcyBjb3VudFxuICAgIGlmIChzaWduZWRVcmwpIHtcbiAgICAgIC8vIFJldHVybiBwcmVzaWduZWQgVVJMIGZvciBzaW5nbGUgc2NlbmVcbiAgICAgIGNvbnN0IGdldE9iamVjdENvbW1hbmQgPSBuZXcgR2V0T2JqZWN0Q29tbWFuZCh7XG4gICAgICAgIEJ1Y2tldDogcHJvY2Vzcy5lbnYuVklERU9fUEFSVFNfQlVDS0VUX05BTUUhLFxuICAgICAgICBLZXk6IHMzS2V5LFxuICAgICAgfSk7XG5cbiAgICAgIGNvbnN0IHByZXNpZ25lZFVybCA9IGF3YWl0IGdldFNpZ25lZFVybChzMywgZ2V0T2JqZWN0Q29tbWFuZCwge1xuICAgICAgICBleHBpcmVzSW46IDM2MDAwLCAvLyAxMCBob3Vyc1xuICAgICAgfSk7XG5cbiAgICAgIGNvbnNvbGUubG9nKFxuICAgICAgICAn8J+WvO+4jyBnZW5haSAtIEdlbmVyYXRlZCBhbmQgdXBsb2FkZWQgaW1hZ2Ugd2l0aCBwcmVzaWduZWQgVVJMOicsXG4gICAgICAgIHByZXNpZ25lZFVybCxcbiAgICAgICk7XG5cbiAgICAgIHJldHVybiBwcmVzaWduZWRVcmw7XG4gICAgfVxuXG4gICAgcmV0dXJuICcnO1xuICB9IGNhdGNoIChlcnJvcikge1xuICAgIGNvbnNvbGUuZXJyb3IoXG4gICAgICBg4p2MIGdlbmFpIC0gRXJyb3IgaW4gZ2VuZXJhdGVOYW5vQmFuYW5hSW1hZ2UgZm9yIHNjZW5lICR7c2NlbmVQb3NpdGlvbn06YCxcbiAgICAgIGVycm9yLFxuICAgICk7XG4gICAgaWYgKGVycm9yICYmIHR5cGVvZiBlcnJvciA9PT0gJ29iamVjdCcgJiYgJ21lc3NhZ2UnIGluIGVycm9yKSB7XG4gICAgICBjb25zb2xlLmVycm9yKCdnZW5haSAtIEVycm9yIG1lc3NhZ2U6JywgZXJyb3IubWVzc2FnZSk7XG4gICAgICBjb25zb2xlLmVycm9yKCdnZW5haSAtIEVycm9yIG5hbWU6JywgKGVycm9yIGFzIGFueSkubmFtZSk7XG4gICAgICBjb25zb2xlLmVycm9yKCdnZW5haSAtIEVycm9yIHN0YWNrOicsIChlcnJvciBhcyBhbnkpLnN0YWNrKTtcbiAgICB9XG4gICAgdGhyb3cgZXJyb3I7XG4gIH1cbn1cbiJdfQ==