"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateNanoBananaImage = generateNanoBananaImage;
const genai_1 = require("@google/genai");
const client_s3_1 = require("@aws-sdk/client-s3");
const s3_request_presigner_1 = require("@aws-sdk/s3-request-presigner");
const s3 = new client_s3_1.S3Client({ region: process.env.AWS_REGION || 'us-east-1' });
async function generateNanoBananaImage(description, scenePosition, userId, timestamp, seed, signedUrl) {
    try {
        // Initialize Google GenAI
        const genAI = new genai_1.GoogleGenAI({
            apiKey: process.env.GEMINI_API_KEY,
        });
        console.log(`🎨  genai - Calling Gemini Nano Banana for image generation in scene ${scenePosition}...`);
        console.log('- Prompt:', description);
        console.log('- Model: gemini-2.5-flash-image-preview');
        console.log('- User ID:', userId);
        console.log('- Timestamp:', timestamp);
        console.log('- Seed:', seed);
        // Generate an image using Gemini Nano Banana
        console.log('🎨 genai - Generating image from text...');
        // Retry logic for image generation
        let response;
        let retryCount = 0;
        const maxRetries = 5;
        const timeoutMs = 60000; // 60 seconds timeout
        while (retryCount < maxRetries) {
            try {
                console.log(`🎨 genai - Attempt ${retryCount + 1}/${maxRetries} for scene ${scenePosition}`);
                response = (await Promise.race([
                    genAI.models.generateImages({
                        model: 'imagen-4.0-generate-001',
                        prompt: description,
                        config: {
                            numberOfImages: 1,
                            aspectRatio: '9:16',
                            personGeneration: genai_1.PersonGeneration.ALLOW_ALL,
                        },
                    }),
                    new Promise((_, reject) => setTimeout(() => reject(new Error('Image generation timeout')), timeoutMs)),
                ]));
                console.log('🎨 genai - Image generation API call completed');
                console.log('🔍 genai - Response received, checking for generated images...');
                console.log('🔍 genai - Generated images count:', response.generatedImages?.length || 0);
                console.log('genai - promptFeedback:', response?.promptFeedback);
                console.log('genai - safetyRatings:', response?.safetyRatings);
                console.log('genai - blockedReason:', response?.blockedReason || response?.finishReason);
                if (!response.generatedImages ||
                    response.generatedImages.length === 0) {
                    throw new Error('No images generated by the API');
                }
                // If we get here, the generation was successful
                console.log('✅ genai - Image generation successful');
                break;
            }
            catch (error) {
                retryCount++;
                console.error(`❌ genai - Image generation attempt ${retryCount} failed:`, error);
                // If we've exhausted retries, throw the error
                if (retryCount >= maxRetries) {
                    console.error(`❌ genai - All ${maxRetries} attempts failed for scene ${scenePosition}`);
                    throw error;
                }
                // Wait before retrying (exponential backoff)
                const waitTime = Math.min(1000 * Math.pow(2, retryCount - 1), 5000);
                console.log(`⏳ genai - Waiting ${waitTime}ms before retry...`);
                await new Promise((resolve) => setTimeout(resolve, waitTime));
            }
        }
        let s3Key = '';
        for (const generatedImage of response.generatedImages || []) {
            let imgBytes = generatedImage.image?.imageBytes;
            const imageBuffer = Buffer.from(imgBytes || '', 'base64');
            console.log('genai - Image saved as gemini-native-image.png');
            // if you want to always store JPEG, actually re-encode with `sharp`.
            // otherwise keep the model's format:
            s3Key = `${userId}/${timestamp}.scene-${scenePosition}.png`;
            console.log('genai - Uploading image to S3', s3Key);
            await s3.send(new client_s3_1.PutObjectCommand({
                Bucket: process.env.VIDEO_PARTS_BUCKET_NAME,
                Key: s3Key,
                Body: imageBuffer,
                ContentType: 'image/png',
            }));
            console.log('genai - Image uploaded to S3', s3Key);
        }
        // Generate URL based on scenes count
        if (signedUrl) {
            // Return presigned URL for single scene
            const getObjectCommand = new client_s3_1.GetObjectCommand({
                Bucket: process.env.VIDEO_PARTS_BUCKET_NAME,
                Key: s3Key,
            });
            const presignedUrl = await (0, s3_request_presigner_1.getSignedUrl)(s3, getObjectCommand, {
                expiresIn: 36000, // 10 hours
            });
            console.log('🖼️ genai - Generated and uploaded image with presigned URL:', presignedUrl);
            return presignedUrl;
        }
        return '';
    }
    catch (error) {
        console.error(`❌ genai - Error in generateNanoBananaImage for scene ${scenePosition}:`, error);
        if (error && typeof error === 'object' && 'message' in error) {
            console.error('genai - Error message:', error.message);
            console.error('genai - Error name:', error.name);
            console.error('genai - Error stack:', error.stack);
        }
        throw error;
    }
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW1hZ2VOYW5vQmFuYW5hLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiaW1hZ2VOYW5vQmFuYW5hLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7O0FBaUJBLDBEQXFLQztBQXRMRCx5Q0FBOEQ7QUFDOUQsa0RBSTRCO0FBQzVCLHdFQUE2RDtBQUU3RCxNQUFNLEVBQUUsR0FBRyxJQUFJLG9CQUFRLENBQUMsRUFBRSxNQUFNLEVBQUUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxVQUFVLElBQUksV0FBVyxFQUFFLENBQUMsQ0FBQztBQVNwRSxLQUFLLFVBQVUsdUJBQXVCLENBQzNDLFdBQW1CLEVBQ25CLGFBQXFCLEVBQ3JCLE1BQWMsRUFDZCxTQUFpQixFQUNqQixJQUFZLEVBQ1osU0FBbUI7SUFFbkIsSUFBSSxDQUFDO1FBQ0gsMEJBQTBCO1FBQzFCLE1BQU0sS0FBSyxHQUFHLElBQUksbUJBQVcsQ0FBQztZQUM1QixNQUFNLEVBQUUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxjQUFlO1NBQ3BDLENBQUMsQ0FBQztRQUVILE9BQU8sQ0FBQyxHQUFHLENBQ1Qsd0VBQXdFLGFBQWEsS0FBSyxDQUMzRixDQUFDO1FBQ0YsT0FBTyxDQUFDLEdBQUcsQ0FBQyxXQUFXLEVBQUUsV0FBVyxDQUFDLENBQUM7UUFDdEMsT0FBTyxDQUFDLEdBQUcsQ0FBQyx5Q0FBeUMsQ0FBQyxDQUFDO1FBQ3ZELE9BQU8sQ0FBQyxHQUFHLENBQUMsWUFBWSxFQUFFLE1BQU0sQ0FBQyxDQUFDO1FBQ2xDLE9BQU8sQ0FBQyxHQUFHLENBQUMsY0FBYyxFQUFFLFNBQVMsQ0FBQyxDQUFDO1FBQ3ZDLE9BQU8sQ0FBQyxHQUFHLENBQUMsU0FBUyxFQUFFLElBQUksQ0FBQyxDQUFDO1FBRTdCLDZDQUE2QztRQUM3QyxPQUFPLENBQUMsR0FBRyxDQUFDLDBDQUEwQyxDQUFDLENBQUM7UUFFeEQsbUNBQW1DO1FBQ25DLElBQUksUUFBUSxDQUFDO1FBQ2IsSUFBSSxVQUFVLEdBQUcsQ0FBQyxDQUFDO1FBQ25CLE1BQU0sVUFBVSxHQUFHLENBQUMsQ0FBQztRQUNyQixNQUFNLFNBQVMsR0FBRyxLQUFLLENBQUMsQ0FBQyxxQkFBcUI7UUFFOUMsT0FBTyxVQUFVLEdBQUcsVUFBVSxFQUFFLENBQUM7WUFDL0IsSUFBSSxDQUFDO2dCQUNILE9BQU8sQ0FBQyxHQUFHLENBQ1Qsc0JBQ0UsVUFBVSxHQUFHLENBQ2YsSUFBSSxVQUFVLGNBQWMsYUFBYSxFQUFFLENBQzVDLENBQUM7Z0JBRUYsUUFBUSxHQUFHLENBQUMsTUFBTSxPQUFPLENBQUMsSUFBSSxDQUFDO29CQUM3QixLQUFLLENBQUMsTUFBTSxDQUFDLGNBQWMsQ0FBQzt3QkFDMUIsS0FBSyxFQUFFLHlCQUF5Qjt3QkFDaEMsTUFBTSxFQUFFLFdBQVc7d0JBQ25CLE1BQU0sRUFBRTs0QkFDTixjQUFjLEVBQUUsQ0FBQzs0QkFDakIsV0FBVyxFQUFFLE1BQU07NEJBQ25CLGdCQUFnQixFQUFFLHdCQUFnQixDQUFDLFNBQVM7eUJBQzdDO3FCQUNGLENBQUM7b0JBQ0YsSUFBSSxPQUFPLENBQUMsQ0FBQyxDQUFDLEVBQUUsTUFBTSxFQUFFLEVBQUUsQ0FDeEIsVUFBVSxDQUNSLEdBQUcsRUFBRSxDQUFDLE1BQU0sQ0FBQyxJQUFJLEtBQUssQ0FBQywwQkFBMEIsQ0FBQyxDQUFDLEVBQ25ELFNBQVMsQ0FDVixDQUNGO2lCQUNGLENBQUMsQ0FBUSxDQUFDO2dCQUVYLE9BQU8sQ0FBQyxHQUFHLENBQUMsZ0RBQWdELENBQUMsQ0FBQztnQkFDOUQsT0FBTyxDQUFDLEdBQUcsQ0FDVCxnRUFBZ0UsQ0FDakUsQ0FBQztnQkFDRixPQUFPLENBQUMsR0FBRyxDQUNULG9DQUFvQyxFQUNwQyxRQUFRLENBQUMsZUFBZSxFQUFFLE1BQU0sSUFBSSxDQUFDLENBQ3RDLENBQUM7Z0JBRUYsT0FBTyxDQUFDLEdBQUcsQ0FBQyx5QkFBeUIsRUFBRSxRQUFRLEVBQUUsY0FBYyxDQUFDLENBQUM7Z0JBQ2pFLE9BQU8sQ0FBQyxHQUFHLENBQUMsd0JBQXdCLEVBQUUsUUFBUSxFQUFFLGFBQWEsQ0FBQyxDQUFDO2dCQUMvRCxPQUFPLENBQUMsR0FBRyxDQUNULHdCQUF3QixFQUN4QixRQUFRLEVBQUUsYUFBYSxJQUFJLFFBQVEsRUFBRSxZQUFZLENBQ2xELENBQUM7Z0JBRUYsSUFDRSxDQUFDLFFBQVEsQ0FBQyxlQUFlO29CQUN6QixRQUFRLENBQUMsZUFBZSxDQUFDLE1BQU0sS0FBSyxDQUFDLEVBQ3JDLENBQUM7b0JBQ0QsTUFBTSxJQUFJLEtBQUssQ0FBQyxnQ0FBZ0MsQ0FBQyxDQUFDO2dCQUNwRCxDQUFDO2dCQUVELGdEQUFnRDtnQkFDaEQsT0FBTyxDQUFDLEdBQUcsQ0FBQyx1Q0FBdUMsQ0FBQyxDQUFDO2dCQUNyRCxNQUFNO1lBQ1IsQ0FBQztZQUFDLE9BQU8sS0FBSyxFQUFFLENBQUM7Z0JBQ2YsVUFBVSxFQUFFLENBQUM7Z0JBQ2IsT0FBTyxDQUFDLEtBQUssQ0FDWCxzQ0FBc0MsVUFBVSxVQUFVLEVBQzFELEtBQUssQ0FDTixDQUFDO2dCQUVGLDhDQUE4QztnQkFDOUMsSUFBSSxVQUFVLElBQUksVUFBVSxFQUFFLENBQUM7b0JBQzdCLE9BQU8sQ0FBQyxLQUFLLENBQ1gsaUJBQWlCLFVBQVUsOEJBQThCLGFBQWEsRUFBRSxDQUN6RSxDQUFDO29CQUNGLE1BQU0sS0FBSyxDQUFDO2dCQUNkLENBQUM7Z0JBRUQsNkNBQTZDO2dCQUM3QyxNQUFNLFFBQVEsR0FBRyxJQUFJLENBQUMsR0FBRyxDQUFDLElBQUksR0FBRyxJQUFJLENBQUMsR0FBRyxDQUFDLENBQUMsRUFBRSxVQUFVLEdBQUcsQ0FBQyxDQUFDLEVBQUUsSUFBSSxDQUFDLENBQUM7Z0JBQ3BFLE9BQU8sQ0FBQyxHQUFHLENBQUMscUJBQXFCLFFBQVEsb0JBQW9CLENBQUMsQ0FBQztnQkFDL0QsTUFBTSxJQUFJLE9BQU8sQ0FBQyxDQUFDLE9BQU8sRUFBRSxFQUFFLENBQUMsVUFBVSxDQUFDLE9BQU8sRUFBRSxRQUFRLENBQUMsQ0FBQyxDQUFDO1lBQ2hFLENBQUM7UUFDSCxDQUFDO1FBRUQsSUFBSSxLQUFLLEdBQUcsRUFBRSxDQUFDO1FBRWYsS0FBSyxNQUFNLGNBQWMsSUFBSSxRQUFRLENBQUMsZUFBZSxJQUFJLEVBQUUsRUFBRSxDQUFDO1lBQzVELElBQUksUUFBUSxHQUFHLGNBQWMsQ0FBQyxLQUFLLEVBQUUsVUFBVSxDQUFDO1lBQ2hELE1BQU0sV0FBVyxHQUFHLE1BQU0sQ0FBQyxJQUFJLENBQUMsUUFBUSxJQUFJLEVBQUUsRUFBRSxRQUFRLENBQUMsQ0FBQztZQUUxRCxPQUFPLENBQUMsR0FBRyxDQUFDLGdEQUFnRCxDQUFDLENBQUM7WUFFOUQscUVBQXFFO1lBQ3JFLHFDQUFxQztZQUNyQyxLQUFLLEdBQUcsR0FBRyxNQUFNLElBQUksU0FBUyxVQUFVLGFBQWEsTUFBTSxDQUFDO1lBRTVELE9BQU8sQ0FBQyxHQUFHLENBQUMsK0JBQStCLEVBQUUsS0FBSyxDQUFDLENBQUM7WUFFcEQsTUFBTSxFQUFFLENBQUMsSUFBSSxDQUNYLElBQUksNEJBQWdCLENBQUM7Z0JBQ25CLE1BQU0sRUFBRSxPQUFPLENBQUMsR0FBRyxDQUFDLHVCQUF3QjtnQkFDNUMsR0FBRyxFQUFFLEtBQUs7Z0JBQ1YsSUFBSSxFQUFFLFdBQVc7Z0JBQ2pCLFdBQVcsRUFBRSxXQUFXO2FBQ3pCLENBQUMsQ0FDSCxDQUFDO1lBRUYsT0FBTyxDQUFDLEdBQUcsQ0FBQyw4QkFBOEIsRUFBRSxLQUFLLENBQUMsQ0FBQztRQUNyRCxDQUFDO1FBRUQscUNBQXFDO1FBQ3JDLElBQUksU0FBUyxFQUFFLENBQUM7WUFDZCx3Q0FBd0M7WUFDeEMsTUFBTSxnQkFBZ0IsR0FBRyxJQUFJLDRCQUFnQixDQUFDO2dCQUM1QyxNQUFNLEVBQUUsT0FBTyxDQUFDLEdBQUcsQ0FBQyx1QkFBd0I7Z0JBQzVDLEdBQUcsRUFBRSxLQUFLO2FBQ1gsQ0FBQyxDQUFDO1lBRUgsTUFBTSxZQUFZLEdBQUcsTUFBTSxJQUFBLG1DQUFZLEVBQUMsRUFBRSxFQUFFLGdCQUFnQixFQUFFO2dCQUM1RCxTQUFTLEVBQUUsS0FBSyxFQUFFLFdBQVc7YUFDOUIsQ0FBQyxDQUFDO1lBRUgsT0FBTyxDQUFDLEdBQUcsQ0FDVCw4REFBOEQsRUFDOUQsWUFBWSxDQUNiLENBQUM7WUFFRixPQUFPLFlBQVksQ0FBQztRQUN0QixDQUFDO1FBRUQsT0FBTyxFQUFFLENBQUM7SUFDWixDQUFDO0lBQUMsT0FBTyxLQUFLLEVBQUUsQ0FBQztRQUNmLE9BQU8sQ0FBQyxLQUFLLENBQ1gsd0RBQXdELGFBQWEsR0FBRyxFQUN4RSxLQUFLLENBQ04sQ0FBQztRQUNGLElBQUksS0FBSyxJQUFJLE9BQU8sS0FBSyxLQUFLLFFBQVEsSUFBSSxTQUFTLElBQUksS0FBSyxFQUFFLENBQUM7WUFDN0QsT0FBTyxDQUFDLEtBQUssQ0FBQyx3QkFBd0IsRUFBRSxLQUFLLENBQUMsT0FBTyxDQUFDLENBQUM7WUFDdkQsT0FBTyxDQUFDLEtBQUssQ0FBQyxxQkFBcUIsRUFBRyxLQUFhLENBQUMsSUFBSSxDQUFDLENBQUM7WUFDMUQsT0FBTyxDQUFDLEtBQUssQ0FBQyxzQkFBc0IsRUFBRyxLQUFhLENBQUMsS0FBSyxDQUFDLENBQUM7UUFDOUQsQ0FBQztRQUNELE1BQU0sS0FBSyxDQUFDO0lBQ2QsQ0FBQztBQUNILENBQUMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBHb29nbGVHZW5BSSwgUGVyc29uR2VuZXJhdGlvbiB9IGZyb20gJ0Bnb29nbGUvZ2VuYWknO1xuaW1wb3J0IHtcbiAgUzNDbGllbnQsXG4gIFB1dE9iamVjdENvbW1hbmQsXG4gIEdldE9iamVjdENvbW1hbmQsXG59IGZyb20gJ0Bhd3Mtc2RrL2NsaWVudC1zMyc7XG5pbXBvcnQgeyBnZXRTaWduZWRVcmwgfSBmcm9tICdAYXdzLXNkay9zMy1yZXF1ZXN0LXByZXNpZ25lcic7XG5cbmNvbnN0IHMzID0gbmV3IFMzQ2xpZW50KHsgcmVnaW9uOiBwcm9jZXNzLmVudi5BV1NfUkVHSU9OIHx8ICd1cy1lYXN0LTEnIH0pO1xuXG5leHBvcnQgaW50ZXJmYWNlIFNjZW5lIHtcbiAgZGVzY3JpcHRpb246IHN0cmluZztcbiAgZHVyYXRpb246IG51bWJlcjtcbiAgbmFycmF0aW9uOiBzdHJpbmc7XG4gIGlkOiBudW1iZXI7XG59XG5cbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBnZW5lcmF0ZU5hbm9CYW5hbmFJbWFnZShcbiAgZGVzY3JpcHRpb246IHN0cmluZyxcbiAgc2NlbmVQb3NpdGlvbjogbnVtYmVyLFxuICB1c2VySWQ6IHN0cmluZyxcbiAgdGltZXN0YW1wOiBzdHJpbmcsXG4gIHNlZWQ6IG51bWJlcixcbiAgc2lnbmVkVXJsPzogYm9vbGVhbixcbik6IFByb21pc2U8c3RyaW5nIHwgbnVsbD4ge1xuICB0cnkge1xuICAgIC8vIEluaXRpYWxpemUgR29vZ2xlIEdlbkFJXG4gICAgY29uc3QgZ2VuQUkgPSBuZXcgR29vZ2xlR2VuQUkoe1xuICAgICAgYXBpS2V5OiBwcm9jZXNzLmVudi5HRU1JTklfQVBJX0tFWSEsXG4gICAgfSk7XG5cbiAgICBjb25zb2xlLmxvZyhcbiAgICAgIGDwn46oICBnZW5haSAtIENhbGxpbmcgR2VtaW5pIE5hbm8gQmFuYW5hIGZvciBpbWFnZSBnZW5lcmF0aW9uIGluIHNjZW5lICR7c2NlbmVQb3NpdGlvbn0uLi5gLFxuICAgICk7XG4gICAgY29uc29sZS5sb2coJy0gUHJvbXB0OicsIGRlc2NyaXB0aW9uKTtcbiAgICBjb25zb2xlLmxvZygnLSBNb2RlbDogZ2VtaW5pLTIuNS1mbGFzaC1pbWFnZS1wcmV2aWV3Jyk7XG4gICAgY29uc29sZS5sb2coJy0gVXNlciBJRDonLCB1c2VySWQpO1xuICAgIGNvbnNvbGUubG9nKCctIFRpbWVzdGFtcDonLCB0aW1lc3RhbXApO1xuICAgIGNvbnNvbGUubG9nKCctIFNlZWQ6Jywgc2VlZCk7XG5cbiAgICAvLyBHZW5lcmF0ZSBhbiBpbWFnZSB1c2luZyBHZW1pbmkgTmFubyBCYW5hbmFcbiAgICBjb25zb2xlLmxvZygn8J+OqCBnZW5haSAtIEdlbmVyYXRpbmcgaW1hZ2UgZnJvbSB0ZXh0Li4uJyk7XG5cbiAgICAvLyBSZXRyeSBsb2dpYyBmb3IgaW1hZ2UgZ2VuZXJhdGlvblxuICAgIGxldCByZXNwb25zZTtcbiAgICBsZXQgcmV0cnlDb3VudCA9IDA7XG4gICAgY29uc3QgbWF4UmV0cmllcyA9IDU7XG4gICAgY29uc3QgdGltZW91dE1zID0gNjAwMDA7IC8vIDYwIHNlY29uZHMgdGltZW91dFxuXG4gICAgd2hpbGUgKHJldHJ5Q291bnQgPCBtYXhSZXRyaWVzKSB7XG4gICAgICB0cnkge1xuICAgICAgICBjb25zb2xlLmxvZyhcbiAgICAgICAgICBg8J+OqCBnZW5haSAtIEF0dGVtcHQgJHtcbiAgICAgICAgICAgIHJldHJ5Q291bnQgKyAxXG4gICAgICAgICAgfS8ke21heFJldHJpZXN9IGZvciBzY2VuZSAke3NjZW5lUG9zaXRpb259YCxcbiAgICAgICAgKTtcblxuICAgICAgICByZXNwb25zZSA9IChhd2FpdCBQcm9taXNlLnJhY2UoW1xuICAgICAgICAgIGdlbkFJLm1vZGVscy5nZW5lcmF0ZUltYWdlcyh7XG4gICAgICAgICAgICBtb2RlbDogJ2ltYWdlbi00LjAtZ2VuZXJhdGUtMDAxJyxcbiAgICAgICAgICAgIHByb21wdDogZGVzY3JpcHRpb24sXG4gICAgICAgICAgICBjb25maWc6IHtcbiAgICAgICAgICAgICAgbnVtYmVyT2ZJbWFnZXM6IDEsXG4gICAgICAgICAgICAgIGFzcGVjdFJhdGlvOiAnOToxNicsXG4gICAgICAgICAgICAgIHBlcnNvbkdlbmVyYXRpb246IFBlcnNvbkdlbmVyYXRpb24uQUxMT1dfQUxMLFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICB9KSxcbiAgICAgICAgICBuZXcgUHJvbWlzZSgoXywgcmVqZWN0KSA9PlxuICAgICAgICAgICAgc2V0VGltZW91dChcbiAgICAgICAgICAgICAgKCkgPT4gcmVqZWN0KG5ldyBFcnJvcignSW1hZ2UgZ2VuZXJhdGlvbiB0aW1lb3V0JykpLFxuICAgICAgICAgICAgICB0aW1lb3V0TXMsXG4gICAgICAgICAgICApLFxuICAgICAgICAgICksXG4gICAgICAgIF0pKSBhcyBhbnk7XG5cbiAgICAgICAgY29uc29sZS5sb2coJ/CfjqggZ2VuYWkgLSBJbWFnZSBnZW5lcmF0aW9uIEFQSSBjYWxsIGNvbXBsZXRlZCcpO1xuICAgICAgICBjb25zb2xlLmxvZyhcbiAgICAgICAgICAn8J+UjSBnZW5haSAtIFJlc3BvbnNlIHJlY2VpdmVkLCBjaGVja2luZyBmb3IgZ2VuZXJhdGVkIGltYWdlcy4uLicsXG4gICAgICAgICk7XG4gICAgICAgIGNvbnNvbGUubG9nKFxuICAgICAgICAgICfwn5SNIGdlbmFpIC0gR2VuZXJhdGVkIGltYWdlcyBjb3VudDonLFxuICAgICAgICAgIHJlc3BvbnNlLmdlbmVyYXRlZEltYWdlcz8ubGVuZ3RoIHx8IDAsXG4gICAgICAgICk7XG5cbiAgICAgICAgY29uc29sZS5sb2coJ2dlbmFpIC0gcHJvbXB0RmVlZGJhY2s6JywgcmVzcG9uc2U/LnByb21wdEZlZWRiYWNrKTtcbiAgICAgICAgY29uc29sZS5sb2coJ2dlbmFpIC0gc2FmZXR5UmF0aW5nczonLCByZXNwb25zZT8uc2FmZXR5UmF0aW5ncyk7XG4gICAgICAgIGNvbnNvbGUubG9nKFxuICAgICAgICAgICdnZW5haSAtIGJsb2NrZWRSZWFzb246JyxcbiAgICAgICAgICByZXNwb25zZT8uYmxvY2tlZFJlYXNvbiB8fCByZXNwb25zZT8uZmluaXNoUmVhc29uLFxuICAgICAgICApO1xuXG4gICAgICAgIGlmIChcbiAgICAgICAgICAhcmVzcG9uc2UuZ2VuZXJhdGVkSW1hZ2VzIHx8XG4gICAgICAgICAgcmVzcG9uc2UuZ2VuZXJhdGVkSW1hZ2VzLmxlbmd0aCA9PT0gMFxuICAgICAgICApIHtcbiAgICAgICAgICB0aHJvdyBuZXcgRXJyb3IoJ05vIGltYWdlcyBnZW5lcmF0ZWQgYnkgdGhlIEFQSScpO1xuICAgICAgICB9XG5cbiAgICAgICAgLy8gSWYgd2UgZ2V0IGhlcmUsIHRoZSBnZW5lcmF0aW9uIHdhcyBzdWNjZXNzZnVsXG4gICAgICAgIGNvbnNvbGUubG9nKCfinIUgZ2VuYWkgLSBJbWFnZSBnZW5lcmF0aW9uIHN1Y2Nlc3NmdWwnKTtcbiAgICAgICAgYnJlYWs7XG4gICAgICB9IGNhdGNoIChlcnJvcikge1xuICAgICAgICByZXRyeUNvdW50Kys7XG4gICAgICAgIGNvbnNvbGUuZXJyb3IoXG4gICAgICAgICAgYOKdjCBnZW5haSAtIEltYWdlIGdlbmVyYXRpb24gYXR0ZW1wdCAke3JldHJ5Q291bnR9IGZhaWxlZDpgLFxuICAgICAgICAgIGVycm9yLFxuICAgICAgICApO1xuXG4gICAgICAgIC8vIElmIHdlJ3ZlIGV4aGF1c3RlZCByZXRyaWVzLCB0aHJvdyB0aGUgZXJyb3JcbiAgICAgICAgaWYgKHJldHJ5Q291bnQgPj0gbWF4UmV0cmllcykge1xuICAgICAgICAgIGNvbnNvbGUuZXJyb3IoXG4gICAgICAgICAgICBg4p2MIGdlbmFpIC0gQWxsICR7bWF4UmV0cmllc30gYXR0ZW1wdHMgZmFpbGVkIGZvciBzY2VuZSAke3NjZW5lUG9zaXRpb259YCxcbiAgICAgICAgICApO1xuICAgICAgICAgIHRocm93IGVycm9yO1xuICAgICAgICB9XG5cbiAgICAgICAgLy8gV2FpdCBiZWZvcmUgcmV0cnlpbmcgKGV4cG9uZW50aWFsIGJhY2tvZmYpXG4gICAgICAgIGNvbnN0IHdhaXRUaW1lID0gTWF0aC5taW4oMTAwMCAqIE1hdGgucG93KDIsIHJldHJ5Q291bnQgLSAxKSwgNTAwMCk7XG4gICAgICAgIGNvbnNvbGUubG9nKGDij7MgZ2VuYWkgLSBXYWl0aW5nICR7d2FpdFRpbWV9bXMgYmVmb3JlIHJldHJ5Li4uYCk7XG4gICAgICAgIGF3YWl0IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiBzZXRUaW1lb3V0KHJlc29sdmUsIHdhaXRUaW1lKSk7XG4gICAgICB9XG4gICAgfVxuXG4gICAgbGV0IHMzS2V5ID0gJyc7XG5cbiAgICBmb3IgKGNvbnN0IGdlbmVyYXRlZEltYWdlIG9mIHJlc3BvbnNlLmdlbmVyYXRlZEltYWdlcyB8fCBbXSkge1xuICAgICAgbGV0IGltZ0J5dGVzID0gZ2VuZXJhdGVkSW1hZ2UuaW1hZ2U/LmltYWdlQnl0ZXM7XG4gICAgICBjb25zdCBpbWFnZUJ1ZmZlciA9IEJ1ZmZlci5mcm9tKGltZ0J5dGVzIHx8ICcnLCAnYmFzZTY0Jyk7XG5cbiAgICAgIGNvbnNvbGUubG9nKCdnZW5haSAtIEltYWdlIHNhdmVkIGFzIGdlbWluaS1uYXRpdmUtaW1hZ2UucG5nJyk7XG5cbiAgICAgIC8vIGlmIHlvdSB3YW50IHRvIGFsd2F5cyBzdG9yZSBKUEVHLCBhY3R1YWxseSByZS1lbmNvZGUgd2l0aCBgc2hhcnBgLlxuICAgICAgLy8gb3RoZXJ3aXNlIGtlZXAgdGhlIG1vZGVsJ3MgZm9ybWF0OlxuICAgICAgczNLZXkgPSBgJHt1c2VySWR9LyR7dGltZXN0YW1wfS5zY2VuZS0ke3NjZW5lUG9zaXRpb259LnBuZ2A7XG5cbiAgICAgIGNvbnNvbGUubG9nKCdnZW5haSAtIFVwbG9hZGluZyBpbWFnZSB0byBTMycsIHMzS2V5KTtcblxuICAgICAgYXdhaXQgczMuc2VuZChcbiAgICAgICAgbmV3IFB1dE9iamVjdENvbW1hbmQoe1xuICAgICAgICAgIEJ1Y2tldDogcHJvY2Vzcy5lbnYuVklERU9fUEFSVFNfQlVDS0VUX05BTUUhLFxuICAgICAgICAgIEtleTogczNLZXksXG4gICAgICAgICAgQm9keTogaW1hZ2VCdWZmZXIsXG4gICAgICAgICAgQ29udGVudFR5cGU6ICdpbWFnZS9wbmcnLFxuICAgICAgICB9KSxcbiAgICAgICk7XG5cbiAgICAgIGNvbnNvbGUubG9nKCdnZW5haSAtIEltYWdlIHVwbG9hZGVkIHRvIFMzJywgczNLZXkpO1xuICAgIH1cblxuICAgIC8vIEdlbmVyYXRlIFVSTCBiYXNlZCBvbiBzY2VuZXMgY291bnRcbiAgICBpZiAoc2lnbmVkVXJsKSB7XG4gICAgICAvLyBSZXR1cm4gcHJlc2lnbmVkIFVSTCBmb3Igc2luZ2xlIHNjZW5lXG4gICAgICBjb25zdCBnZXRPYmplY3RDb21tYW5kID0gbmV3IEdldE9iamVjdENvbW1hbmQoe1xuICAgICAgICBCdWNrZXQ6IHByb2Nlc3MuZW52LlZJREVPX1BBUlRTX0JVQ0tFVF9OQU1FISxcbiAgICAgICAgS2V5OiBzM0tleSxcbiAgICAgIH0pO1xuXG4gICAgICBjb25zdCBwcmVzaWduZWRVcmwgPSBhd2FpdCBnZXRTaWduZWRVcmwoczMsIGdldE9iamVjdENvbW1hbmQsIHtcbiAgICAgICAgZXhwaXJlc0luOiAzNjAwMCwgLy8gMTAgaG91cnNcbiAgICAgIH0pO1xuXG4gICAgICBjb25zb2xlLmxvZyhcbiAgICAgICAgJ/CflrzvuI8gZ2VuYWkgLSBHZW5lcmF0ZWQgYW5kIHVwbG9hZGVkIGltYWdlIHdpdGggcHJlc2lnbmVkIFVSTDonLFxuICAgICAgICBwcmVzaWduZWRVcmwsXG4gICAgICApO1xuXG4gICAgICByZXR1cm4gcHJlc2lnbmVkVXJsO1xuICAgIH1cblxuICAgIHJldHVybiAnJztcbiAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICBjb25zb2xlLmVycm9yKFxuICAgICAgYOKdjCBnZW5haSAtIEVycm9yIGluIGdlbmVyYXRlTmFub0JhbmFuYUltYWdlIGZvciBzY2VuZSAke3NjZW5lUG9zaXRpb259OmAsXG4gICAgICBlcnJvcixcbiAgICApO1xuICAgIGlmIChlcnJvciAmJiB0eXBlb2YgZXJyb3IgPT09ICdvYmplY3QnICYmICdtZXNzYWdlJyBpbiBlcnJvcikge1xuICAgICAgY29uc29sZS5lcnJvcignZ2VuYWkgLSBFcnJvciBtZXNzYWdlOicsIGVycm9yLm1lc3NhZ2UpO1xuICAgICAgY29uc29sZS5lcnJvcignZ2VuYWkgLSBFcnJvciBuYW1lOicsIChlcnJvciBhcyBhbnkpLm5hbWUpO1xuICAgICAgY29uc29sZS5lcnJvcignZ2VuYWkgLSBFcnJvciBzdGFjazonLCAoZXJyb3IgYXMgYW55KS5zdGFjayk7XG4gICAgfVxuICAgIHRocm93IGVycm9yO1xuICB9XG59XG4iXX0=