import { GoogleGenAI, PersonGeneration } from '@google/genai';
import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  ListObjectsV2Command,
  CopyObjectCommand,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

const s3 = new S3Client({ region: process.env.AWS_REGION || 'us-east-1' });

export interface Scene {
  description: string;
  duration: number;
  narration: string;
  id: number;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function mockGenerateImage(
  scenePosition: number,
  userId: string,
  timestamp: string,
  signedUrl?: boolean,
): Promise<string | null> {
  const delayMs = 2000 + Math.random() * 3000;
  console.log(
    `🎭 MOCK - simulating image generation for scene ${scenePosition} (${Math.round(
      delayMs,
    )}ms delay)`,
  );
  await sleep(delayMs);

  const listResponse = await s3.send(
    new ListObjectsV2Command({
      Bucket: process.env.VIDEO_PARTS_BUCKET_NAME!,
    }),
  );

  const candidates = (listResponse.Contents || [])
    .filter((obj) => obj.Key?.endsWith('.png'))
    .sort(
      (a, b) =>
        (b.LastModified?.getTime() || 0) - (a.LastModified?.getTime() || 0),
    )
    .slice(0, 20);

  if (candidates.length === 0) {
    throw new Error(
      'MOCK_IMAGE_GENERATION is enabled but no existing .png images were found in the bucket to reuse',
    );
  }

  const sourceKey =
    candidates[Math.floor(Math.random() * candidates.length)].Key!;
  const destKey = `${userId}/${timestamp}.scene-${scenePosition}.png`;

  console.log(`🎭 MOCK - reusing existing image ${sourceKey} for scene ${scenePosition}`);

  await s3.send(
    new CopyObjectCommand({
      Bucket: process.env.VIDEO_PARTS_BUCKET_NAME!,
      CopySource: `${process.env.VIDEO_PARTS_BUCKET_NAME}/${sourceKey}`,
      Key: destKey,
    }),
  );

  if (signedUrl) {
    const presignedUrl = await getSignedUrl(
      s3,
      new GetObjectCommand({
        Bucket: process.env.VIDEO_PARTS_BUCKET_NAME!,
        Key: destKey,
      }),
      { expiresIn: 36000 },
    );
    console.log('🎭 MOCK - returning presigned URL:', presignedUrl);
    return presignedUrl;
  }

  return '';
}

export async function generateNanoBananaImage(
  description: string,
  scenePosition: number,
  userId: string,
  timestamp: string,
  seed: number,
  signedUrl?: boolean,
): Promise<string | null> {
  if (process.env.MOCK_IMAGE_GENERATION === 'true') {
    return await mockGenerateImage(scenePosition, userId, timestamp, signedUrl);
  }

  try {
    // Initialize Google GenAI
    const genAI = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY!,
    });

    console.log(
      `🎨  genai - Calling Gemini Nano Banana for image generation in scene ${scenePosition}...`,
    );
    console.log('- Prompt:', description);
    console.log('- Model: gemini-2.5-flash-image-preview');
    console.log('- User ID:', userId);
    console.log('- Timestamp:', timestamp);
    console.log('- Seed:', seed);

    // Generate an image using Gemini Nano Banana
    console.log('🎨 genai - Generating image from text...');

    // Retry logic for image generation
    let response;
    let retryCount = 0;
    const maxRetries = 5;
    const timeoutMs = 60000; // 60 seconds timeout

    while (retryCount < maxRetries) {
      try {
        console.log(
          `🎨 genai - Attempt ${
            retryCount + 1
          }/${maxRetries} for scene ${scenePosition}`,
        );

        // TODO: imagen-4.0-fast-generate-001 (and the rest of the Imagen 4 family)
        // is deprecated and shuts down 2026-08-17 — migrate before then.
        response = (await Promise.race([
          genAI.models.generateImages({
            model: 'imagen-4.0-fast-generate-001',
            prompt: description,
            config: {
              numberOfImages: 1,
              aspectRatio: '9:16',
              personGeneration: PersonGeneration.ALLOW_ALL,
            },
          }),
          new Promise((_, reject) =>
            setTimeout(
              () => reject(new Error('Image generation timeout')),
              timeoutMs,
            ),
          ),
        ])) as any;

        console.log('🎨 genai - Image generation API call completed');
        console.log(
          '🔍 genai - Response received, checking for generated images...',
        );
        console.log(
          '🔍 genai - Generated images count:',
          response.generatedImages?.length || 0,
        );

        console.log('genai - promptFeedback:', response?.promptFeedback);
        console.log('genai - safetyRatings:', response?.safetyRatings);
        console.log(
          'genai - blockedReason:',
          response?.blockedReason || response?.finishReason,
        );

        if (
          !response.generatedImages ||
          response.generatedImages.length === 0
        ) {
          throw new Error('No images generated by the API');
        }

        // If we get here, the generation was successful
        console.log('✅ genai - Image generation successful');
        break;
      } catch (error) {
        retryCount++;
        console.error(
          `❌ genai - Image generation attempt ${retryCount} failed:`,
          error,
        );

        // If we've exhausted retries, throw the error
        if (retryCount >= maxRetries) {
          console.error(
            `❌ genai - All ${maxRetries} attempts failed for scene ${scenePosition}`,
          );
          throw error;
        }

        // Wait before retrying (exponential backoff)
        const waitTime = Math.min(1000 * Math.pow(2, retryCount - 1), 5000);
        console.log(`⏳ genai - Waiting ${waitTime}ms before retry...`);
        await new Promise((resolve) => setTimeout(resolve, waitTime));
      }
    }

    let s3Key = '';

    for (const generatedImage of response.generatedImages || []) {
      let imgBytes = generatedImage.image?.imageBytes;
      const imageBuffer = Buffer.from(imgBytes || '', 'base64');

      console.log('genai - Image saved as gemini-native-image.png');

      // if you want to always store JPEG, actually re-encode with `sharp`.
      // otherwise keep the model's format:
      s3Key = `${userId}/${timestamp}.scene-${scenePosition}.png`;

      console.log('genai - Uploading image to S3', s3Key);

      await s3.send(
        new PutObjectCommand({
          Bucket: process.env.VIDEO_PARTS_BUCKET_NAME!,
          Key: s3Key,
          Body: imageBuffer,
          ContentType: 'image/png',
        }),
      );

      console.log('genai - Image uploaded to S3', s3Key);
    }

    // Generate URL based on scenes count
    if (signedUrl) {
      // Return presigned URL for single scene
      const getObjectCommand = new GetObjectCommand({
        Bucket: process.env.VIDEO_PARTS_BUCKET_NAME!,
        Key: s3Key,
      });

      const presignedUrl = await getSignedUrl(s3, getObjectCommand, {
        expiresIn: 36000, // 10 hours
      });

      console.log(
        '🖼️ genai - Generated and uploaded image with presigned URL:',
        presignedUrl,
      );

      return presignedUrl;
    }

    return '';
  } catch (error) {
    console.error(
      `❌ genai - Error in generateNanoBananaImage for scene ${scenePosition}:`,
      error,
    );
    if (error && typeof error === 'object' && 'message' in error) {
      console.error('genai - Error message:', error.message);
      console.error('genai - Error name:', (error as any).name);
      console.error('genai - Error stack:', (error as any).stack);
    }
    throw error;
  }
}
