"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateNanoBananaImage = generateNanoBananaImage;
const genai_1 = require("@google/genai");
const client_s3_1 = require("@aws-sdk/client-s3");
const s3_request_presigner_1 = require("@aws-sdk/s3-request-presigner");
const s3 = new client_s3_1.S3Client({ region: process.env.AWS_REGION || 'us-east-1' });
async function generateNanoBananaImage(description, scenePosition, userId, timestamp, seed, signedUrl) {
    try {
        // Initialize Google GenAI
        const genAI = new genai_1.GoogleGenAI({
            apiKey: process.env.GEMINI_API_KEY,
        });
        console.log(`🎨  genai - Calling Gemini Nano Banana for image generation in scene ${scenePosition}...`);
        console.log('- Prompt:', description);
        console.log('- Model: gemini-2.5-flash-image-preview');
        console.log('- User ID:', userId);
        console.log('- Timestamp:', timestamp);
        console.log('- Seed:', seed);
        // Generate an image using Gemini Nano Banana
        console.log('🎨 genai - Generating image from text...');
        const prompt = `anime-style: ${description}`;
        // Retry logic for image generation
        let response;
        let retryCount = 0;
        const maxRetries = 5;
        const timeoutMs = 60000; // 60 seconds timeout
        while (retryCount < maxRetries) {
            try {
                console.log(`🎨 genai - Attempt ${retryCount + 1}/${maxRetries} for scene ${scenePosition}`);
                response = (await Promise.race([
                    genAI.models.generateImages({
                        model: 'imagen-4.0-generate-001',
                        prompt,
                        config: {
                            numberOfImages: 1,
                            aspectRatio: '9:16',
                            personGeneration: genai_1.PersonGeneration.ALLOW_ALL,
                        },
                    }),
                    new Promise((_, reject) => setTimeout(() => reject(new Error('Image generation timeout')), timeoutMs)),
                ]));
                console.log('🎨 genai - Image generation API call completed');
                console.log('🔍 genai - Response received, checking for generated images...');
                console.log('🔍 genai - Generated images count:', response.generatedImages?.length || 0);
                console.log('genai - promptFeedback:', response?.promptFeedback);
                console.log('genai - safetyRatings:', response?.safetyRatings);
                console.log('genai - blockedReason:', response?.blockedReason || response?.finishReason);
                if (!response.generatedImages ||
                    response.generatedImages.length === 0) {
                    throw new Error('No images generated by the API');
                }
                // If we get here, the generation was successful
                console.log('✅ genai - Image generation successful');
                break;
            }
            catch (error) {
                retryCount++;
                console.error(`❌ genai - Image generation attempt ${retryCount} failed:`, error);
                // If we've exhausted retries, throw the error
                if (retryCount >= maxRetries) {
                    console.error(`❌ genai - All ${maxRetries} attempts failed for scene ${scenePosition}`);
                    throw error;
                }
                // Wait before retrying (exponential backoff)
                const waitTime = Math.min(1000 * Math.pow(2, retryCount - 1), 5000);
                console.log(`⏳ genai - Waiting ${waitTime}ms before retry...`);
                await new Promise((resolve) => setTimeout(resolve, waitTime));
            }
        }
        let s3Key = '';
        for (const generatedImage of response.generatedImages || []) {
            let imgBytes = generatedImage.image?.imageBytes;
            const imageBuffer = Buffer.from(imgBytes || '', 'base64');
            console.log('genai - Image saved as gemini-native-image.png');
            // if you want to always store JPEG, actually re-encode with `sharp`.
            // otherwise keep the model's format:
            s3Key = `${userId}/${timestamp}.scene-${scenePosition}.png`;
            console.log('genai - Uploading image to S3', s3Key);
            await s3.send(new client_s3_1.PutObjectCommand({
                Bucket: process.env.VIDEO_PARTS_BUCKET_NAME,
                Key: s3Key,
                Body: imageBuffer,
                ContentType: 'image/png',
            }));
            console.log('genai - Image uploaded to S3', s3Key);
        }
        // Generate URL based on scenes count
        if (signedUrl) {
            // Return presigned URL for single scene
            const getObjectCommand = new client_s3_1.GetObjectCommand({
                Bucket: process.env.VIDEO_PARTS_BUCKET_NAME,
                Key: s3Key,
            });
            const presignedUrl = await (0, s3_request_presigner_1.getSignedUrl)(s3, getObjectCommand, {
                expiresIn: 36000, // 10 hours
            });
            console.log('🖼️ genai - Generated and uploaded image with presigned URL:', presignedUrl);
            return presignedUrl;
        }
        return '';
    }
    catch (error) {
        console.error(`❌ genai - Error in generateNanoBananaImage for scene ${scenePosition}:`, error);
        if (error && typeof error === 'object' && 'message' in error) {
            console.error('genai - Error message:', error.message);
            console.error('genai - Error name:', error.name);
            console.error('genai - Error stack:', error.stack);
        }
        throw error;
    }
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW1hZ2VOYW5vQmFuYW5hLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiaW1hZ2VOYW5vQmFuYW5hLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7O0FBaUJBLDBEQXVLQztBQXhMRCx5Q0FBOEQ7QUFDOUQsa0RBSTRCO0FBQzVCLHdFQUE2RDtBQUU3RCxNQUFNLEVBQUUsR0FBRyxJQUFJLG9CQUFRLENBQUMsRUFBRSxNQUFNLEVBQUUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxVQUFVLElBQUksV0FBVyxFQUFFLENBQUMsQ0FBQztBQVNwRSxLQUFLLFVBQVUsdUJBQXVCLENBQzNDLFdBQW1CLEVBQ25CLGFBQXFCLEVBQ3JCLE1BQWMsRUFDZCxTQUFpQixFQUNqQixJQUFZLEVBQ1osU0FBbUI7SUFFbkIsSUFBSSxDQUFDO1FBQ0gsMEJBQTBCO1FBQzFCLE1BQU0sS0FBSyxHQUFHLElBQUksbUJBQVcsQ0FBQztZQUM1QixNQUFNLEVBQUUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxjQUFlO1NBQ3BDLENBQUMsQ0FBQztRQUVILE9BQU8sQ0FBQyxHQUFHLENBQ1Qsd0VBQXdFLGFBQWEsS0FBSyxDQUMzRixDQUFDO1FBQ0YsT0FBTyxDQUFDLEdBQUcsQ0FBQyxXQUFXLEVBQUUsV0FBVyxDQUFDLENBQUM7UUFDdEMsT0FBTyxDQUFDLEdBQUcsQ0FBQyx5Q0FBeUMsQ0FBQyxDQUFDO1FBQ3ZELE9BQU8sQ0FBQyxHQUFHLENBQUMsWUFBWSxFQUFFLE1BQU0sQ0FBQyxDQUFDO1FBQ2xDLE9BQU8sQ0FBQyxHQUFHLENBQUMsY0FBYyxFQUFFLFNBQVMsQ0FBQyxDQUFDO1FBQ3ZDLE9BQU8sQ0FBQyxHQUFHLENBQUMsU0FBUyxFQUFFLElBQUksQ0FBQyxDQUFDO1FBRTdCLDZDQUE2QztRQUM3QyxPQUFPLENBQUMsR0FBRyxDQUFDLDBDQUEwQyxDQUFDLENBQUM7UUFFeEQsTUFBTSxNQUFNLEdBQUcsZ0JBQWdCLFdBQVcsRUFBRSxDQUFDO1FBRTdDLG1DQUFtQztRQUNuQyxJQUFJLFFBQVEsQ0FBQztRQUNiLElBQUksVUFBVSxHQUFHLENBQUMsQ0FBQztRQUNuQixNQUFNLFVBQVUsR0FBRyxDQUFDLENBQUM7UUFDckIsTUFBTSxTQUFTLEdBQUcsS0FBSyxDQUFDLENBQUMscUJBQXFCO1FBRTlDLE9BQU8sVUFBVSxHQUFHLFVBQVUsRUFBRSxDQUFDO1lBQy9CLElBQUksQ0FBQztnQkFDSCxPQUFPLENBQUMsR0FBRyxDQUNULHNCQUNFLFVBQVUsR0FBRyxDQUNmLElBQUksVUFBVSxjQUFjLGFBQWEsRUFBRSxDQUM1QyxDQUFDO2dCQUVGLFFBQVEsR0FBRyxDQUFDLE1BQU0sT0FBTyxDQUFDLElBQUksQ0FBQztvQkFDN0IsS0FBSyxDQUFDLE1BQU0sQ0FBQyxjQUFjLENBQUM7d0JBQzFCLEtBQUssRUFBRSx5QkFBeUI7d0JBQ2hDLE1BQU07d0JBQ04sTUFBTSxFQUFFOzRCQUNOLGNBQWMsRUFBRSxDQUFDOzRCQUNqQixXQUFXLEVBQUUsTUFBTTs0QkFDbkIsZ0JBQWdCLEVBQUUsd0JBQWdCLENBQUMsU0FBUzt5QkFDN0M7cUJBQ0YsQ0FBQztvQkFDRixJQUFJLE9BQU8sQ0FBQyxDQUFDLENBQUMsRUFBRSxNQUFNLEVBQUUsRUFBRSxDQUN4QixVQUFVLENBQ1IsR0FBRyxFQUFFLENBQUMsTUFBTSxDQUFDLElBQUksS0FBSyxDQUFDLDBCQUEwQixDQUFDLENBQUMsRUFDbkQsU0FBUyxDQUNWLENBQ0Y7aUJBQ0YsQ0FBQyxDQUFRLENBQUM7Z0JBRVgsT0FBTyxDQUFDLEdBQUcsQ0FBQyxnREFBZ0QsQ0FBQyxDQUFDO2dCQUM5RCxPQUFPLENBQUMsR0FBRyxDQUNULGdFQUFnRSxDQUNqRSxDQUFDO2dCQUNGLE9BQU8sQ0FBQyxHQUFHLENBQ1Qsb0NBQW9DLEVBQ3BDLFFBQVEsQ0FBQyxlQUFlLEVBQUUsTUFBTSxJQUFJLENBQUMsQ0FDdEMsQ0FBQztnQkFFRixPQUFPLENBQUMsR0FBRyxDQUFDLHlCQUF5QixFQUFFLFFBQVEsRUFBRSxjQUFjLENBQUMsQ0FBQztnQkFDakUsT0FBTyxDQUFDLEdBQUcsQ0FBQyx3QkFBd0IsRUFBRSxRQUFRLEVBQUUsYUFBYSxDQUFDLENBQUM7Z0JBQy9ELE9BQU8sQ0FBQyxHQUFHLENBQ1Qsd0JBQXdCLEVBQ3hCLFFBQVEsRUFBRSxhQUFhLElBQUksUUFBUSxFQUFFLFlBQVksQ0FDbEQsQ0FBQztnQkFFRixJQUNFLENBQUMsUUFBUSxDQUFDLGVBQWU7b0JBQ3pCLFFBQVEsQ0FBQyxlQUFlLENBQUMsTUFBTSxLQUFLLENBQUMsRUFDckMsQ0FBQztvQkFDRCxNQUFNLElBQUksS0FBSyxDQUFDLGdDQUFnQyxDQUFDLENBQUM7Z0JBQ3BELENBQUM7Z0JBRUQsZ0RBQWdEO2dCQUNoRCxPQUFPLENBQUMsR0FBRyxDQUFDLHVDQUF1QyxDQUFDLENBQUM7Z0JBQ3JELE1BQU07WUFDUixDQUFDO1lBQUMsT0FBTyxLQUFLLEVBQUUsQ0FBQztnQkFDZixVQUFVLEVBQUUsQ0FBQztnQkFDYixPQUFPLENBQUMsS0FBSyxDQUNYLHNDQUFzQyxVQUFVLFVBQVUsRUFDMUQsS0FBSyxDQUNOLENBQUM7Z0JBRUYsOENBQThDO2dCQUM5QyxJQUFJLFVBQVUsSUFBSSxVQUFVLEVBQUUsQ0FBQztvQkFDN0IsT0FBTyxDQUFDLEtBQUssQ0FDWCxpQkFBaUIsVUFBVSw4QkFBOEIsYUFBYSxFQUFFLENBQ3pFLENBQUM7b0JBQ0YsTUFBTSxLQUFLLENBQUM7Z0JBQ2QsQ0FBQztnQkFFRCw2Q0FBNkM7Z0JBQzdDLE1BQU0sUUFBUSxHQUFHLElBQUksQ0FBQyxHQUFHLENBQUMsSUFBSSxHQUFHLElBQUksQ0FBQyxHQUFHLENBQUMsQ0FBQyxFQUFFLFVBQVUsR0FBRyxDQUFDLENBQUMsRUFBRSxJQUFJLENBQUMsQ0FBQztnQkFDcEUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxxQkFBcUIsUUFBUSxvQkFBb0IsQ0FBQyxDQUFDO2dCQUMvRCxNQUFNLElBQUksT0FBTyxDQUFDLENBQUMsT0FBTyxFQUFFLEVBQUUsQ0FBQyxVQUFVLENBQUMsT0FBTyxFQUFFLFFBQVEsQ0FBQyxDQUFDLENBQUM7WUFDaEUsQ0FBQztRQUNILENBQUM7UUFFRCxJQUFJLEtBQUssR0FBRyxFQUFFLENBQUM7UUFFZixLQUFLLE1BQU0sY0FBYyxJQUFJLFFBQVEsQ0FBQyxlQUFlLElBQUksRUFBRSxFQUFFLENBQUM7WUFDNUQsSUFBSSxRQUFRLEdBQUcsY0FBYyxDQUFDLEtBQUssRUFBRSxVQUFVLENBQUM7WUFDaEQsTUFBTSxXQUFXLEdBQUcsTUFBTSxDQUFDLElBQUksQ0FBQyxRQUFRLElBQUksRUFBRSxFQUFFLFFBQVEsQ0FBQyxDQUFDO1lBRTFELE9BQU8sQ0FBQyxHQUFHLENBQUMsZ0RBQWdELENBQUMsQ0FBQztZQUU5RCxxRUFBcUU7WUFDckUscUNBQXFDO1lBQ3JDLEtBQUssR0FBRyxHQUFHLE1BQU0sSUFBSSxTQUFTLFVBQVUsYUFBYSxNQUFNLENBQUM7WUFFNUQsT0FBTyxDQUFDLEdBQUcsQ0FBQywrQkFBK0IsRUFBRSxLQUFLLENBQUMsQ0FBQztZQUVwRCxNQUFNLEVBQUUsQ0FBQyxJQUFJLENBQ1gsSUFBSSw0QkFBZ0IsQ0FBQztnQkFDbkIsTUFBTSxFQUFFLE9BQU8sQ0FBQyxHQUFHLENBQUMsdUJBQXdCO2dCQUM1QyxHQUFHLEVBQUUsS0FBSztnQkFDVixJQUFJLEVBQUUsV0FBVztnQkFDakIsV0FBVyxFQUFFLFdBQVc7YUFDekIsQ0FBQyxDQUNILENBQUM7WUFFRixPQUFPLENBQUMsR0FBRyxDQUFDLDhCQUE4QixFQUFFLEtBQUssQ0FBQyxDQUFDO1FBQ3JELENBQUM7UUFFRCxxQ0FBcUM7UUFDckMsSUFBSSxTQUFTLEVBQUUsQ0FBQztZQUNkLHdDQUF3QztZQUN4QyxNQUFNLGdCQUFnQixHQUFHLElBQUksNEJBQWdCLENBQUM7Z0JBQzVDLE1BQU0sRUFBRSxPQUFPLENBQUMsR0FBRyxDQUFDLHVCQUF3QjtnQkFDNUMsR0FBRyxFQUFFLEtBQUs7YUFDWCxDQUFDLENBQUM7WUFFSCxNQUFNLFlBQVksR0FBRyxNQUFNLElBQUEsbUNBQVksRUFBQyxFQUFFLEVBQUUsZ0JBQWdCLEVBQUU7Z0JBQzVELFNBQVMsRUFBRSxLQUFLLEVBQUUsV0FBVzthQUM5QixDQUFDLENBQUM7WUFFSCxPQUFPLENBQUMsR0FBRyxDQUNULDhEQUE4RCxFQUM5RCxZQUFZLENBQ2IsQ0FBQztZQUVGLE9BQU8sWUFBWSxDQUFDO1FBQ3RCLENBQUM7UUFFRCxPQUFPLEVBQUUsQ0FBQztJQUNaLENBQUM7SUFBQyxPQUFPLEtBQUssRUFBRSxDQUFDO1FBQ2YsT0FBTyxDQUFDLEtBQUssQ0FDWCx3REFBd0QsYUFBYSxHQUFHLEVBQ3hFLEtBQUssQ0FDTixDQUFDO1FBQ0YsSUFBSSxLQUFLLElBQUksT0FBTyxLQUFLLEtBQUssUUFBUSxJQUFJLFNBQVMsSUFBSSxLQUFLLEVBQUUsQ0FBQztZQUM3RCxPQUFPLENBQUMsS0FBSyxDQUFDLHdCQUF3QixFQUFFLEtBQUssQ0FBQyxPQUFPLENBQUMsQ0FBQztZQUN2RCxPQUFPLENBQUMsS0FBSyxDQUFDLHFCQUFxQixFQUFHLEtBQWEsQ0FBQyxJQUFJLENBQUMsQ0FBQztZQUMxRCxPQUFPLENBQUMsS0FBSyxDQUFDLHNCQUFzQixFQUFHLEtBQWEsQ0FBQyxLQUFLLENBQUMsQ0FBQztRQUM5RCxDQUFDO1FBQ0QsTUFBTSxLQUFLLENBQUM7SUFDZCxDQUFDO0FBQ0gsQ0FBQyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IEdvb2dsZUdlbkFJLCBQZXJzb25HZW5lcmF0aW9uIH0gZnJvbSAnQGdvb2dsZS9nZW5haSc7XG5pbXBvcnQge1xuICBTM0NsaWVudCxcbiAgUHV0T2JqZWN0Q29tbWFuZCxcbiAgR2V0T2JqZWN0Q29tbWFuZCxcbn0gZnJvbSAnQGF3cy1zZGsvY2xpZW50LXMzJztcbmltcG9ydCB7IGdldFNpZ25lZFVybCB9IGZyb20gJ0Bhd3Mtc2RrL3MzLXJlcXVlc3QtcHJlc2lnbmVyJztcblxuY29uc3QgczMgPSBuZXcgUzNDbGllbnQoeyByZWdpb246IHByb2Nlc3MuZW52LkFXU19SRUdJT04gfHwgJ3VzLWVhc3QtMScgfSk7XG5cbmV4cG9ydCBpbnRlcmZhY2UgU2NlbmUge1xuICBkZXNjcmlwdGlvbjogc3RyaW5nO1xuICBkdXJhdGlvbjogbnVtYmVyO1xuICBuYXJyYXRpb246IHN0cmluZztcbiAgaWQ6IG51bWJlcjtcbn1cblxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIGdlbmVyYXRlTmFub0JhbmFuYUltYWdlKFxuICBkZXNjcmlwdGlvbjogc3RyaW5nLFxuICBzY2VuZVBvc2l0aW9uOiBudW1iZXIsXG4gIHVzZXJJZDogc3RyaW5nLFxuICB0aW1lc3RhbXA6IHN0cmluZyxcbiAgc2VlZDogbnVtYmVyLFxuICBzaWduZWRVcmw/OiBib29sZWFuLFxuKTogUHJvbWlzZTxzdHJpbmcgfCBudWxsPiB7XG4gIHRyeSB7XG4gICAgLy8gSW5pdGlhbGl6ZSBHb29nbGUgR2VuQUlcbiAgICBjb25zdCBnZW5BSSA9IG5ldyBHb29nbGVHZW5BSSh7XG4gICAgICBhcGlLZXk6IHByb2Nlc3MuZW52LkdFTUlOSV9BUElfS0VZISxcbiAgICB9KTtcblxuICAgIGNvbnNvbGUubG9nKFxuICAgICAgYPCfjqggIGdlbmFpIC0gQ2FsbGluZyBHZW1pbmkgTmFubyBCYW5hbmEgZm9yIGltYWdlIGdlbmVyYXRpb24gaW4gc2NlbmUgJHtzY2VuZVBvc2l0aW9ufS4uLmAsXG4gICAgKTtcbiAgICBjb25zb2xlLmxvZygnLSBQcm9tcHQ6JywgZGVzY3JpcHRpb24pO1xuICAgIGNvbnNvbGUubG9nKCctIE1vZGVsOiBnZW1pbmktMi41LWZsYXNoLWltYWdlLXByZXZpZXcnKTtcbiAgICBjb25zb2xlLmxvZygnLSBVc2VyIElEOicsIHVzZXJJZCk7XG4gICAgY29uc29sZS5sb2coJy0gVGltZXN0YW1wOicsIHRpbWVzdGFtcCk7XG4gICAgY29uc29sZS5sb2coJy0gU2VlZDonLCBzZWVkKTtcblxuICAgIC8vIEdlbmVyYXRlIGFuIGltYWdlIHVzaW5nIEdlbWluaSBOYW5vIEJhbmFuYVxuICAgIGNvbnNvbGUubG9nKCfwn46oIGdlbmFpIC0gR2VuZXJhdGluZyBpbWFnZSBmcm9tIHRleHQuLi4nKTtcblxuICAgIGNvbnN0IHByb21wdCA9IGBhbmltZS1zdHlsZTogJHtkZXNjcmlwdGlvbn1gO1xuXG4gICAgLy8gUmV0cnkgbG9naWMgZm9yIGltYWdlIGdlbmVyYXRpb25cbiAgICBsZXQgcmVzcG9uc2U7XG4gICAgbGV0IHJldHJ5Q291bnQgPSAwO1xuICAgIGNvbnN0IG1heFJldHJpZXMgPSA1O1xuICAgIGNvbnN0IHRpbWVvdXRNcyA9IDYwMDAwOyAvLyA2MCBzZWNvbmRzIHRpbWVvdXRcblxuICAgIHdoaWxlIChyZXRyeUNvdW50IDwgbWF4UmV0cmllcykge1xuICAgICAgdHJ5IHtcbiAgICAgICAgY29uc29sZS5sb2coXG4gICAgICAgICAgYPCfjqggZ2VuYWkgLSBBdHRlbXB0ICR7XG4gICAgICAgICAgICByZXRyeUNvdW50ICsgMVxuICAgICAgICAgIH0vJHttYXhSZXRyaWVzfSBmb3Igc2NlbmUgJHtzY2VuZVBvc2l0aW9ufWAsXG4gICAgICAgICk7XG5cbiAgICAgICAgcmVzcG9uc2UgPSAoYXdhaXQgUHJvbWlzZS5yYWNlKFtcbiAgICAgICAgICBnZW5BSS5tb2RlbHMuZ2VuZXJhdGVJbWFnZXMoe1xuICAgICAgICAgICAgbW9kZWw6ICdpbWFnZW4tNC4wLWdlbmVyYXRlLTAwMScsXG4gICAgICAgICAgICBwcm9tcHQsXG4gICAgICAgICAgICBjb25maWc6IHtcbiAgICAgICAgICAgICAgbnVtYmVyT2ZJbWFnZXM6IDEsXG4gICAgICAgICAgICAgIGFzcGVjdFJhdGlvOiAnOToxNicsXG4gICAgICAgICAgICAgIHBlcnNvbkdlbmVyYXRpb246IFBlcnNvbkdlbmVyYXRpb24uQUxMT1dfQUxMLFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICB9KSxcbiAgICAgICAgICBuZXcgUHJvbWlzZSgoXywgcmVqZWN0KSA9PlxuICAgICAgICAgICAgc2V0VGltZW91dChcbiAgICAgICAgICAgICAgKCkgPT4gcmVqZWN0KG5ldyBFcnJvcignSW1hZ2UgZ2VuZXJhdGlvbiB0aW1lb3V0JykpLFxuICAgICAgICAgICAgICB0aW1lb3V0TXMsXG4gICAgICAgICAgICApLFxuICAgICAgICAgICksXG4gICAgICAgIF0pKSBhcyBhbnk7XG5cbiAgICAgICAgY29uc29sZS5sb2coJ/CfjqggZ2VuYWkgLSBJbWFnZSBnZW5lcmF0aW9uIEFQSSBjYWxsIGNvbXBsZXRlZCcpO1xuICAgICAgICBjb25zb2xlLmxvZyhcbiAgICAgICAgICAn8J+UjSBnZW5haSAtIFJlc3BvbnNlIHJlY2VpdmVkLCBjaGVja2luZyBmb3IgZ2VuZXJhdGVkIGltYWdlcy4uLicsXG4gICAgICAgICk7XG4gICAgICAgIGNvbnNvbGUubG9nKFxuICAgICAgICAgICfwn5SNIGdlbmFpIC0gR2VuZXJhdGVkIGltYWdlcyBjb3VudDonLFxuICAgICAgICAgIHJlc3BvbnNlLmdlbmVyYXRlZEltYWdlcz8ubGVuZ3RoIHx8IDAsXG4gICAgICAgICk7XG5cbiAgICAgICAgY29uc29sZS5sb2coJ2dlbmFpIC0gcHJvbXB0RmVlZGJhY2s6JywgcmVzcG9uc2U/LnByb21wdEZlZWRiYWNrKTtcbiAgICAgICAgY29uc29sZS5sb2coJ2dlbmFpIC0gc2FmZXR5UmF0aW5nczonLCByZXNwb25zZT8uc2FmZXR5UmF0aW5ncyk7XG4gICAgICAgIGNvbnNvbGUubG9nKFxuICAgICAgICAgICdnZW5haSAtIGJsb2NrZWRSZWFzb246JyxcbiAgICAgICAgICByZXNwb25zZT8uYmxvY2tlZFJlYXNvbiB8fCByZXNwb25zZT8uZmluaXNoUmVhc29uLFxuICAgICAgICApO1xuXG4gICAgICAgIGlmIChcbiAgICAgICAgICAhcmVzcG9uc2UuZ2VuZXJhdGVkSW1hZ2VzIHx8XG4gICAgICAgICAgcmVzcG9uc2UuZ2VuZXJhdGVkSW1hZ2VzLmxlbmd0aCA9PT0gMFxuICAgICAgICApIHtcbiAgICAgICAgICB0aHJvdyBuZXcgRXJyb3IoJ05vIGltYWdlcyBnZW5lcmF0ZWQgYnkgdGhlIEFQSScpO1xuICAgICAgICB9XG5cbiAgICAgICAgLy8gSWYgd2UgZ2V0IGhlcmUsIHRoZSBnZW5lcmF0aW9uIHdhcyBzdWNjZXNzZnVsXG4gICAgICAgIGNvbnNvbGUubG9nKCfinIUgZ2VuYWkgLSBJbWFnZSBnZW5lcmF0aW9uIHN1Y2Nlc3NmdWwnKTtcbiAgICAgICAgYnJlYWs7XG4gICAgICB9IGNhdGNoIChlcnJvcikge1xuICAgICAgICByZXRyeUNvdW50Kys7XG4gICAgICAgIGNvbnNvbGUuZXJyb3IoXG4gICAgICAgICAgYOKdjCBnZW5haSAtIEltYWdlIGdlbmVyYXRpb24gYXR0ZW1wdCAke3JldHJ5Q291bnR9IGZhaWxlZDpgLFxuICAgICAgICAgIGVycm9yLFxuICAgICAgICApO1xuXG4gICAgICAgIC8vIElmIHdlJ3ZlIGV4aGF1c3RlZCByZXRyaWVzLCB0aHJvdyB0aGUgZXJyb3JcbiAgICAgICAgaWYgKHJldHJ5Q291bnQgPj0gbWF4UmV0cmllcykge1xuICAgICAgICAgIGNvbnNvbGUuZXJyb3IoXG4gICAgICAgICAgICBg4p2MIGdlbmFpIC0gQWxsICR7bWF4UmV0cmllc30gYXR0ZW1wdHMgZmFpbGVkIGZvciBzY2VuZSAke3NjZW5lUG9zaXRpb259YCxcbiAgICAgICAgICApO1xuICAgICAgICAgIHRocm93IGVycm9yO1xuICAgICAgICB9XG5cbiAgICAgICAgLy8gV2FpdCBiZWZvcmUgcmV0cnlpbmcgKGV4cG9uZW50aWFsIGJhY2tvZmYpXG4gICAgICAgIGNvbnN0IHdhaXRUaW1lID0gTWF0aC5taW4oMTAwMCAqIE1hdGgucG93KDIsIHJldHJ5Q291bnQgLSAxKSwgNTAwMCk7XG4gICAgICAgIGNvbnNvbGUubG9nKGDij7MgZ2VuYWkgLSBXYWl0aW5nICR7d2FpdFRpbWV9bXMgYmVmb3JlIHJldHJ5Li4uYCk7XG4gICAgICAgIGF3YWl0IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiBzZXRUaW1lb3V0KHJlc29sdmUsIHdhaXRUaW1lKSk7XG4gICAgICB9XG4gICAgfVxuXG4gICAgbGV0IHMzS2V5ID0gJyc7XG5cbiAgICBmb3IgKGNvbnN0IGdlbmVyYXRlZEltYWdlIG9mIHJlc3BvbnNlLmdlbmVyYXRlZEltYWdlcyB8fCBbXSkge1xuICAgICAgbGV0IGltZ0J5dGVzID0gZ2VuZXJhdGVkSW1hZ2UuaW1hZ2U/LmltYWdlQnl0ZXM7XG4gICAgICBjb25zdCBpbWFnZUJ1ZmZlciA9IEJ1ZmZlci5mcm9tKGltZ0J5dGVzIHx8ICcnLCAnYmFzZTY0Jyk7XG5cbiAgICAgIGNvbnNvbGUubG9nKCdnZW5haSAtIEltYWdlIHNhdmVkIGFzIGdlbWluaS1uYXRpdmUtaW1hZ2UucG5nJyk7XG5cbiAgICAgIC8vIGlmIHlvdSB3YW50IHRvIGFsd2F5cyBzdG9yZSBKUEVHLCBhY3R1YWxseSByZS1lbmNvZGUgd2l0aCBgc2hhcnBgLlxuICAgICAgLy8gb3RoZXJ3aXNlIGtlZXAgdGhlIG1vZGVsJ3MgZm9ybWF0OlxuICAgICAgczNLZXkgPSBgJHt1c2VySWR9LyR7dGltZXN0YW1wfS5zY2VuZS0ke3NjZW5lUG9zaXRpb259LnBuZ2A7XG5cbiAgICAgIGNvbnNvbGUubG9nKCdnZW5haSAtIFVwbG9hZGluZyBpbWFnZSB0byBTMycsIHMzS2V5KTtcblxuICAgICAgYXdhaXQgczMuc2VuZChcbiAgICAgICAgbmV3IFB1dE9iamVjdENvbW1hbmQoe1xuICAgICAgICAgIEJ1Y2tldDogcHJvY2Vzcy5lbnYuVklERU9fUEFSVFNfQlVDS0VUX05BTUUhLFxuICAgICAgICAgIEtleTogczNLZXksXG4gICAgICAgICAgQm9keTogaW1hZ2VCdWZmZXIsXG4gICAgICAgICAgQ29udGVudFR5cGU6ICdpbWFnZS9wbmcnLFxuICAgICAgICB9KSxcbiAgICAgICk7XG5cbiAgICAgIGNvbnNvbGUubG9nKCdnZW5haSAtIEltYWdlIHVwbG9hZGVkIHRvIFMzJywgczNLZXkpO1xuICAgIH1cblxuICAgIC8vIEdlbmVyYXRlIFVSTCBiYXNlZCBvbiBzY2VuZXMgY291bnRcbiAgICBpZiAoc2lnbmVkVXJsKSB7XG4gICAgICAvLyBSZXR1cm4gcHJlc2lnbmVkIFVSTCBmb3Igc2luZ2xlIHNjZW5lXG4gICAgICBjb25zdCBnZXRPYmplY3RDb21tYW5kID0gbmV3IEdldE9iamVjdENvbW1hbmQoe1xuICAgICAgICBCdWNrZXQ6IHByb2Nlc3MuZW52LlZJREVPX1BBUlRTX0JVQ0tFVF9OQU1FISxcbiAgICAgICAgS2V5OiBzM0tleSxcbiAgICAgIH0pO1xuXG4gICAgICBjb25zdCBwcmVzaWduZWRVcmwgPSBhd2FpdCBnZXRTaWduZWRVcmwoczMsIGdldE9iamVjdENvbW1hbmQsIHtcbiAgICAgICAgZXhwaXJlc0luOiAzNjAwMCwgLy8gMTAgaG91cnNcbiAgICAgIH0pO1xuXG4gICAgICBjb25zb2xlLmxvZyhcbiAgICAgICAgJ/CflrzvuI8gZ2VuYWkgLSBHZW5lcmF0ZWQgYW5kIHVwbG9hZGVkIGltYWdlIHdpdGggcHJlc2lnbmVkIFVSTDonLFxuICAgICAgICBwcmVzaWduZWRVcmwsXG4gICAgICApO1xuXG4gICAgICByZXR1cm4gcHJlc2lnbmVkVXJsO1xuICAgIH1cblxuICAgIHJldHVybiAnJztcbiAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICBjb25zb2xlLmVycm9yKFxuICAgICAgYOKdjCBnZW5haSAtIEVycm9yIGluIGdlbmVyYXRlTmFub0JhbmFuYUltYWdlIGZvciBzY2VuZSAke3NjZW5lUG9zaXRpb259OmAsXG4gICAgICBlcnJvcixcbiAgICApO1xuICAgIGlmIChlcnJvciAmJiB0eXBlb2YgZXJyb3IgPT09ICdvYmplY3QnICYmICdtZXNzYWdlJyBpbiBlcnJvcikge1xuICAgICAgY29uc29sZS5lcnJvcignZ2VuYWkgLSBFcnJvciBtZXNzYWdlOicsIGVycm9yLm1lc3NhZ2UpO1xuICAgICAgY29uc29sZS5lcnJvcignZ2VuYWkgLSBFcnJvciBuYW1lOicsIChlcnJvciBhcyBhbnkpLm5hbWUpO1xuICAgICAgY29uc29sZS5lcnJvcignZ2VuYWkgLSBFcnJvciBzdGFjazonLCAoZXJyb3IgYXMgYW55KS5zdGFjayk7XG4gICAgfVxuICAgIHRocm93IGVycm9yO1xuICB9XG59XG4iXX0=